export function getPortalBanner(key: string) {
  const map: Record<string, string> = {
    supervisor: '/images/b1.png',
    supervisor_queue: '/images/b2.png',
    supervisor_fleet: '/images/b3.png',
    supervisor_exceptions: '/images/b4.png',
    wayplan: '/images/b5.png',
    wayplan_manifests: '/images/b6.png',
    wayplan_vehicles: '/images/b7.png',
    wayplan_ways: '/images/b8.png',
    wayplan_waybills: '/images/b9.png',
    driver: '/images/b10.png',
    driver_route: '/images/b11.png',
    warehouse: '/images/b12.png',
    warehouse_sorting: '/images/b13.png',
    warehouse_dispatch: '/images/b14.png',
    data_entry: '/images/b15.png',
    data_entry_bulk: '/images/b16.png',
    data_entry_records: '/images/b17.png',
    customer_service: '/images/b1.png',
    customer_service_chat: '/images/b2.png',
    merchant: '/images/b3.png',
    merchant_create: '/images/b4.png',
    merchant_reports: '/images/b5.png',
    customer: '/images/b6.png',
    customer_orders: '/images/b7.png',
    customer_support: '/images/b8.png',
    finance: '/images/b9.png',
    finance_cod: '/images/b10.png',
    finance_invoices: '/images/b11.png',
    hr: '/images/b12.png',
    hr_attendance: '/images/b13.png',
    hr_leave: '/images/b14.png',
    marketing: '/images/b15.png',
    marketing_campaigns: '/images/b16.png',
    marketing_merchants: '/images/b17.png',
    branch_office: '/images/b1.png',
    branch_office_shipments: '/images/b2.png',
    branch_office_team: '/images/b3.png',
    branch_office_finance: '/images/b4.png',
    analytics: '/images/b5.png',
    analytics_revenue: '/images/b6.png',
    analytics_drivers: '/images/b7.png',
    analytics_warehouses: '/images/b8.png',
    analytics_satisfaction: '/images/b9.png',
    settings: '/images/b10.png',
  };
  return map[key] || '/images/b1.png';
}
