-- Britium Waybill Studio V38
-- Batch-level print authorization and enriched parcel print rows.
-- Safe to run after Data Entry V33 and Waybill Studio V37.

create table if not exists public.be_waybill_print_audit_v38 (
  audit_id bigint generated by default as identity primary key,
  pickup_id text not null,
  waybill_no text not null,
  document_type text not null default 'WAYBILL',
  row_count integer not null default 0,
  paper_size text,
  label_size text,
  actor_email text,
  reason text,
  is_reprint boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists be_waybill_print_audit_v38_waybill_idx
  on public.be_waybill_print_audit_v38 (waybill_no, created_at desc);

alter table public.be_waybill_print_audit_v38 enable row level security;
revoke all on public.be_waybill_print_audit_v38 from public, anon, authenticated;

create or replace function public.be_waybill_print_rows_v38(
  p_pickup_id text
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'pickup_id', d.pickup_id,
        'parcel_sequence', d.parcel_sequence,
        'delivery_way_id', d.delivery_way_id,
        'way_id', d.delivery_way_id,
        'tracking_no', d.delivery_way_id,
        'os', coalesce(
          nullif(btrim(p.os), ''),
          nullif(btrim(p.sender_name), ''),
          nullif(btrim(p.merchant_id), ''),
          nullif(btrim(p.customer_id), ''),
          ''
        ),
        'merchant_name', coalesce(
          nullif(btrim(p.os), ''),
          nullif(btrim(p.sender_name), ''),
          nullif(btrim(p.merchant_id), ''),
          nullif(btrim(p.customer_id), ''),
          ''
        ),
        'recipient_name', coalesce(nullif(btrim(p.recipient_name), ''), d.recipient_name, ''),
        'recipient_phone', coalesce(nullif(btrim(p.recipient_phone), ''), d.contact_no_1, ''),
        'contact_no_1', coalesce(nullif(btrim(p.recipient_phone), ''), d.contact_no_1, ''),
        'recipient_address', coalesce(
          nullif(btrim(p.recipient_address), ''),
          nullif(btrim(p.delivery_address), ''),
          d.recipient_address,
          ''
        ),
        'township', coalesce(nullif(btrim(p.township), ''), d.township, ''),
        'recipient_township', coalesce(nullif(btrim(p.township), ''), d.township, ''),
        'destination', coalesce(nullif(btrim(p.destination), ''), d.destination, ''),
        'remarks', coalesce(nullif(btrim(p.remarks), ''), d.remark, ''),
        'remark', coalesce(nullif(btrim(p.remarks), ''), d.remark, ''),
        'customer_tier', d.customer_tier,
        'item_price', coalesce(d.item_price, p.item_price, 0),
        'weight_kg', coalesce(d.weight_kg, p.weight_kg, 0),
        'surcharge', coalesce(d.surcharge, p.extra_weight_charge, 0),
        'delivery_fee', coalesce(d.delivery_fee, p.delivery_charges, 0),
        'delivery_charges', coalesce(d.delivery_fee, p.delivery_charges, 0),
        'cod_amount', coalesce(d.cod_amount, p.cod_amount, 0),
        'actual_collect', coalesce(d.actual_collect, p.collect_amount, 0),
        'collect_amount', coalesce(d.actual_collect, p.collect_amount, 0),
        'status', coalesce(p.status, 'registered'),
        'proof_photo_path', d.proof_photo_path,
        'created_at', coalesce(p.created_at, d.saved_at),
        'updated_at', coalesce(p.updated_at, d.updated_at)
      )
      order by d.parcel_sequence
    ),
    '[]'::jsonb
  )
  from public.be_data_entry_parcel_details d
  left join lateral (
    select p0.*
    from public.parcels p0
    where p0.way_id = d.delivery_way_id
       or p0.tracking_code = d.delivery_way_id
    order by p0.updated_at desc nulls last, p0.created_at desc nulls last
    limit 1
  ) p on true
  where d.pickup_id = p_pickup_id;
$$;

comment on function public.be_waybill_print_rows_v38(text) is
  'Returns enriched Waybill print rows with OS, recipient township and remarks from canonical parcels.';

revoke all on function public.be_waybill_print_rows_v38(text) from public, anon;
grant execute on function public.be_waybill_print_rows_v38(text) to authenticated, service_role;

create or replace function public.be_waybill_authorize_batch_print_v38(
  p_pickup_id text,
  p_waybill_no text,
  p_document_type text default 'WAYBILL',
  p_row_count integer default 0,
  p_paper_size text default null,
  p_label_size text default null,
  p_reason text default '',
  p_actor_email text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pickup_id text := nullif(btrim(coalesce(p_pickup_id, '')), '');
  v_waybill_no text := nullif(btrim(coalesce(p_waybill_no, '')), '');
  v_actor_email text := coalesce(
    nullif(btrim(coalesce(p_actor_email, '')), ''),
    nullif(auth.jwt()->>'email', ''),
    'unknown_operator'
  );
  v_summary record;
  v_prior_count integer := 0;
  v_is_reprint boolean := false;
begin
  if auth.uid() is null then
    return jsonb_build_object(
      'allowed', false,
      'reason_required', false,
      'message', 'Authentication is required before printing.'
    );
  end if;

  if v_pickup_id is null and v_waybill_no is null then
    return jsonb_build_object(
      'allowed', false,
      'reason_required', false,
      'message', 'Pickup ID or batch Waybill number is required.'
    );
  end if;

  select w.pickup_id, w.waybill_no, w.parcel_count, w.status
  into v_summary
  from public.be_parcel_waybills w
  where (v_waybill_no is not null and w.waybill_no = v_waybill_no)
     or (v_pickup_id is not null and w.pickup_id = v_pickup_id)
  order by
    case when v_waybill_no is not null and w.waybill_no = v_waybill_no then 0 else 1 end,
    w.updated_at desc nulls last,
    w.created_at desc nulls last
  limit 1;

  if not found then
    return jsonb_build_object(
      'allowed', false,
      'reason_required', false,
      'message', 'The batch Waybill was not found in be_parcel_waybills.'
    );
  end if;

  v_pickup_id := v_summary.pickup_id;
  v_waybill_no := v_summary.waybill_no;

  select count(*)::integer
  into v_prior_count
  from public.be_waybill_print_audit_v38 a
  where a.waybill_no = v_waybill_no
    and upper(a.document_type) = upper(coalesce(p_document_type, 'WAYBILL'));

  v_is_reprint := v_prior_count > 0;

  if v_is_reprint and nullif(btrim(coalesce(p_reason, '')), '') is null then
    return jsonb_build_object(
      'allowed', false,
      'reason_required', true,
      'pickup_id', v_pickup_id,
      'waybill_no', v_waybill_no,
      'prior_print_count', v_prior_count,
      'message', 'A reprint reason is required because this batch was printed before.'
    );
  end if;

  insert into public.be_waybill_print_audit_v38 (
    pickup_id,
    waybill_no,
    document_type,
    row_count,
    paper_size,
    label_size,
    actor_email,
    reason,
    is_reprint
  ) values (
    v_pickup_id,
    v_waybill_no,
    upper(coalesce(nullif(btrim(p_document_type), ''), 'WAYBILL')),
    greatest(coalesce(p_row_count, 0), 0),
    nullif(btrim(coalesce(p_paper_size, '')), ''),
    nullif(btrim(coalesce(p_label_size, '')), ''),
    v_actor_email,
    nullif(btrim(coalesce(p_reason, '')), ''),
    v_is_reprint
  );

  return jsonb_build_object(
    'allowed', true,
    'reason_required', false,
    'pickup_id', v_pickup_id,
    'waybill_no', v_waybill_no,
    'row_count', greatest(coalesce(p_row_count, 0), 0),
    'is_reprint', v_is_reprint,
    'prior_print_count', v_prior_count,
    'message', case when v_is_reprint then 'Reprint authorized.' else 'Batch print authorized.' end
  );
end;
$$;

comment on function public.be_waybill_authorize_batch_print_v38(text,text,text,integer,text,text,text,text) is
  'Authorizes one pickup-level batch Waybill print job instead of incorrectly authorizing every parcel label separately.';

revoke all on function public.be_waybill_authorize_batch_print_v38(text,text,text,integer,text,text,text,text) from public, anon;
grant execute on function public.be_waybill_authorize_batch_print_v38(text,text,text,integer,text,text,text,text) to authenticated, service_role;

select
  to_regprocedure('public.be_waybill_print_rows_v38(text)')::text as enriched_rows_rpc,
  to_regprocedure('public.be_waybill_authorize_batch_print_v38(text,text,text,integer,text,text,text,text)')::text as batch_print_authorization_rpc,
  to_regclass('public.be_waybill_print_audit_v38')::text as print_audit_table,
  'OS<-parcels.os/sender_name; township<-parcels.township; remarks<-parcels.remarks'::text as print_mapping,
  'one authorization per batch Waybill, not one authorization per parcel row'::text as authorization_strategy;
