-- PARCEL_FINANCIAL_V2_BACKEND_2026-07-31
-- Server-authoritative parcel collection, tariff snapshot, merchant settlement and audit controls.
-- Run in a controlled Supabase/PostgreSQL migration window. Review the exact tariff seed before production.

begin;

create extension if not exists pgcrypto;

do $$
begin
  if to_regclass('public.parcels') is null then
    raise exception 'public.parcels does not exist; aborting PARCEL_FINANCIAL_V2 migration';
  end if;
end
$$;

alter table public.parcels
  add column if not exists customer_tier text,
  add column if not exists monthly_ways integer,
  add column if not exists amount_entry_type text,
  add column if not exists merchant_stated_total_amount bigint,
  add column if not exists additional_customer_charge bigint not null default 0,
  add column if not exists cbm_surcharge bigint not null default 0,
  add column if not exists other_surcharge bigint not null default 0,
  add column if not exists merchant_payable_charges bigint not null default 0,
  add column if not exists other_merchant_credits bigint not null default 0,
  add column if not exists remarks text,
  add column if not exists entered_by uuid,
  add column if not exists authorized_by uuid,
  add column if not exists tariff_zone text,
  add column if not exists tariff_zone_code text,
  add column if not exists base_tariff bigint,
  add column if not exists included_kg numeric(10,3),
  add column if not exists extra_per_kg bigint,
  add column if not exists commitment_min_ways integer,
  add column if not exists commitment_refund_per_way bigint,
  add column if not exists chargeable_weight_kg numeric(10,3),
  add column if not exists extra_kg numeric(10,3),
  add column if not exists weight_surcharge bigint,
  add column if not exists gross_system_delivery_charge bigint,
  add column if not exists commitment_refund bigint,
  add column if not exists net_system_delivery_charge bigint,
  add column if not exists effective_declared_delivery_charge bigint,
  add column if not exists delivery_difference bigint,
  add column if not exists settlement_direction text,
  add column if not exists merchant_settlement_adjustment bigint,
  add column if not exists merchant_final_settlement_amount bigint,
  add column if not exists validation_status text,
  add column if not exists validation_message text,
  add column if not exists calculation_version text not null default 'PARCEL_FINANCIAL_V2',
  add column if not exists calculated_at timestamptz,
  add column if not exists financial_locked_at timestamptz,
  add column if not exists financial_locked_by uuid,
  add column if not exists financial_lock_reason text,
  add column if not exists financial_settlement_batch_id uuid,
  add column if not exists financial_settled_at timestamptz,
  add column if not exists financial_settled_by uuid;

create table if not exists public.be_merchant_financial_profiles_v2 (
  merchant_id text primary key,
  customer_tier text not null,
  is_active boolean not null default true,
  effective_from date not null default current_date,
  effective_to date,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  constraint be_merchant_financial_profiles_v2_tier_check
    check (customer_tier in ('STANDARD','ROYAL','COMMITMENT'))
);

create table if not exists public.be_parcel_tariffs_v2 (
  id bigint generated by default as identity primary key,
  township text not null,
  customer_tier text not null,
  tariff_zone text not null,
  tariff_zone_code text not null,
  base_tariff bigint not null,
  included_kg numeric(10,3) not null,
  extra_per_kg bigint not null,
  commitment_min_ways integer not null default 0,
  commitment_refund_per_way bigint not null default 0,
  note text,
  status text not null default 'ACTIVE',
  effective_from date not null,
  effective_to date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint be_parcel_tariffs_v2_tier_check
    check (customer_tier in ('STANDARD','ROYAL','COMMITMENT')),
  constraint be_parcel_tariffs_v2_status_check
    check (status in ('ACTIVE','INACTIVE')),
  constraint be_parcel_tariffs_v2_amount_check
    check (base_tariff > 0 and included_kg >= 0 and extra_per_kg >= 0
           and commitment_min_ways >= 0 and commitment_refund_per_way >= 0),
  constraint be_parcel_tariffs_v2_version_unique
    unique (township, customer_tier, effective_from)
);

create unique index if not exists be_parcel_tariffs_v2_one_open_active
  on public.be_parcel_tariffs_v2 (lower(btrim(township)), customer_tier)
  where status = 'ACTIVE' and effective_to is null;

insert into public.be_parcel_tariffs_v2 (
  township, customer_tier, tariff_zone, tariff_zone_code,
  base_tariff, included_kg, extra_per_kg,
  commitment_min_ways, commitment_refund_per_way,
  note, status, effective_from
)
values
  ('ပန်းဘဲတန်း', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပန်းဘဲတန်း', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပန်းဘဲတန်း', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ကျောက်တံတား', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ကျောက်တံတား', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ကျောက်တံတား', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('လမ်းမတော်', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('လမ်းမတော်', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('လမ်းမတော်', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('လသာ', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('လသာ', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('လသာ', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပုဇွန်တောင်', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပုဇွန်တောင်', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပုဇွန်တောင်', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဗိုလ်တထောင်', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဗိုလ်တထောင်', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဗိုလ်တထောင်', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဒဂုံ', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဒဂုံ', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဒဂုံ', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('အလုံ', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('အလုံ', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('အလုံ', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ကြည့်မြင်တိုင်', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ကြည့်မြင်တိုင်', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ကြည့်မြင်တိုင်', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('စမ်းချောင်း', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('စမ်းချောင်း', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('စမ်းချောင်း', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('မင်္ဂလာတောင်ညွန့်', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('မင်္ဂလာတောင်ညွန့်', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('မင်္ဂလာတောင်ညွန့်', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('တာမွေ', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('တာမွေ', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('တာမွေ', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဗဟန်း', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဗဟန်း', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဗဟန်း', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('တောင်ဥက္ကလာပ', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('တောင်ဥက္ကလာပ', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('တောင်ဥက္ကလာပ', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('မြောက်ဒဂုံ', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('မြောက်ဒဂုံ', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('မြောက်ဒဂုံ', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('အရှေ့ဒဂုံ', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('အရှေ့ဒဂုံ', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('အရှေ့ဒဂုံ', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ရန်ကင်း', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ရန်ကင်း', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ရန်ကင်း', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ကမာရွတ်', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ကမာရွတ်', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ကမာရွတ်', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('သာကေတ', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('သာကေတ', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('သာကေတ', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('သင်္ဃန်းကျွန်း', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('သင်္ဃန်းကျွန်း', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('သင်္ဃန်းကျွန်း', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('မရမ်းကုန်း', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('မရမ်းကုန်း', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('မရမ်းကုန်း', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('တောင်ဒဂုံ', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('တောင်ဒဂုံ', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('တောင်ဒဂုံ', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဒဂုံဆိပ်ကမ်း', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဒဂုံဆိပ်ကမ်း', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဒဂုံဆိပ်ကမ်း', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဒေါပုံ', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဒေါပုံ', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဒေါပုံ', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('လှိုင်', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('လှိုင်', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('လှိုင်', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('အင်းစိန်', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('အင်းစိန်', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('အင်းစိန်', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('မြောက်ဥက္ကလာပ', 'STANDARD', 'Yangon', 'YGN', 4500, 3.000, 500, 0, 0, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('မြောက်ဥက္ကလာပ', 'ROYAL', 'Yangon', 'YGN', 4500, 5.000, 500, 0, 0, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('မြောက်ဥက္ကလာပ', 'COMMITMENT', 'Yangon', 'YGN', 4500, 5.000, 500, 1500, 500, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('မင်္ဂလာဒုံ', 'STANDARD', 'Yangon', 'YGN', 4500, 3.000, 500, 0, 0, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('မင်္ဂလာဒုံ', 'ROYAL', 'Yangon', 'YGN', 4500, 5.000, 500, 0, 0, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('မင်္ဂလာဒုံ', 'COMMITMENT', 'Yangon', 'YGN', 4500, 5.000, 500, 1500, 500, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('ရွှေပြည်သာ', 'STANDARD', 'Yangon', 'YGN', 4500, 3.000, 500, 0, 0, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('ရွှေပြည်သာ', 'ROYAL', 'Yangon', 'YGN', 4500, 5.000, 500, 0, 0, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('ရွှေပြည်သာ', 'COMMITMENT', 'Yangon', 'YGN', 4500, 5.000, 500, 1500, 500, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('လှိုင်သာယာ', 'STANDARD', 'Yangon', 'YGN', 4500, 3.000, 500, 0, 0, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('လှိုင်သာယာ', 'ROYAL', 'Yangon', 'YGN', 4500, 5.000, 500, 0, 0, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('လှိုင်သာယာ', 'COMMITMENT', 'Yangon', 'YGN', 4500, 5.000, 500, 1500, 500, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('ရွှေပေါက်ကံ', 'STANDARD', 'Yangon', 'YGN', 4500, 3.000, 500, 0, 0, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('ရွှေပေါက်ကံ', 'ROYAL', 'Yangon', 'YGN', 4500, 5.000, 500, 0, 0, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('ရွှေပေါက်ကံ', 'COMMITMENT', 'Yangon', 'YGN', 4500, 5.000, 500, 1500, 500, 'Extended Yangon', 'ACTIVE', DATE '2026-07-31'),
  ('အောင်မင်္ဂလာကားဂိတ်', 'STANDARD', 'Yangon', 'YGN', 3000, 3.000, 500, 0, 0, 'Aung Mingalar highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('အောင်မင်္ဂလာကားဂိတ်', 'ROYAL', 'Yangon', 'YGN', 3000, 5.000, 500, 0, 0, 'Aung Mingalar highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('အောင်မင်္ဂလာကားဂိတ်', 'COMMITMENT', 'Yangon', 'YGN', 3000, 5.000, 500, 1500, 500, 'Aung Mingalar highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('Aung Mingalar Highway Drop Off', 'STANDARD', 'Yangon', 'YGN', 3000, 3.000, 500, 0, 0, 'Aung Mingalar highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('Aung Mingalar Highway Drop Off', 'ROYAL', 'Yangon', 'YGN', 3000, 5.000, 500, 0, 0, 'Aung Mingalar highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('Aung Mingalar Highway Drop Off', 'COMMITMENT', 'Yangon', 'YGN', 3000, 5.000, 500, 1500, 500, 'Aung Mingalar highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('ပရမီ ကားဝင်း (ဗန္ဓုလ)', 'STANDARD', 'Yangon', 'YGN', 3000, 3.000, 500, 0, 0, 'Highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('ပရမီ ကားဝင်း (ဗန္ဓုလ)', 'ROYAL', 'Yangon', 'YGN', 3000, 5.000, 500, 0, 0, 'Highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('ပရမီ ကားဝင်း (ဗန္ဓုလ)', 'COMMITMENT', 'Yangon', 'YGN', 3000, 5.000, 500, 1500, 500, 'Highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('အောင်ဆန်းကွင်း', 'STANDARD', 'Yangon', 'YGN', 3000, 3.000, 500, 0, 0, 'Drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('အောင်ဆန်းကွင်း', 'ROYAL', 'Yangon', 'YGN', 3000, 5.000, 500, 0, 0, 'Drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('အောင်ဆန်းကွင်း', 'COMMITMENT', 'Yangon', 'YGN', 3000, 5.000, 500, 1500, 500, 'Drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('ဂိတ်ချ', 'STANDARD', 'Yangon', 'YGN', 3000, 3.000, 500, 0, 0, 'Drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('ဂိတ်ချ', 'ROYAL', 'Yangon', 'YGN', 3000, 5.000, 500, 0, 0, 'Drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('ဂိတ်ချ', 'COMMITMENT', 'Yangon', 'YGN', 3000, 5.000, 500, 1500, 500, 'Drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('အဝေးပြေး ဂိတ်ချ', 'STANDARD', 'Yangon', 'YGN', 3000, 3.000, 500, 0, 0, 'Highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('အဝေးပြေး ဂိတ်ချ', 'ROYAL', 'Yangon', 'YGN', 3000, 5.000, 500, 0, 0, 'Highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('အဝေးပြေး ဂိတ်ချ', 'COMMITMENT', 'Yangon', 'YGN', 3000, 5.000, 500, 1500, 500, 'Highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('ရန်ကုန်စာတိုက်ကြီး', 'STANDARD', 'Yangon', 'YGN', 3000, 3.000, 500, 0, 0, 'Post office drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('ရန်ကုန်စာတိုက်ကြီး', 'ROYAL', 'Yangon', 'YGN', 3000, 5.000, 500, 0, 0, 'Post office drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('ရန်ကုန်စာတိုက်ကြီး', 'COMMITMENT', 'Yangon', 'YGN', 3000, 5.000, 500, 1500, 500, 'Post office drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('ဘုရင့်နောင် ကားဝင်း', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, 'Bus-station drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('ဘုရင့်နောင် ကားဝင်း', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, 'Bus-station drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('ဘုရင့်နောင် ကားဝင်း', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, 'Bus-station drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('လှိုင်သာယာအဝေးပြေး (ဒဂုံဧရာ)', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, 'Dagon Ayar / Dagon Thiri highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('လှိုင်သာယာအဝေးပြေး (ဒဂုံဧရာ)', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, 'Dagon Ayar / Dagon Thiri highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('လှိုင်သာယာအဝေးပြေး (ဒဂုံဧရာ)', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, 'Dagon Ayar / Dagon Thiri highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('Dagon Thiri Highway Drop Off', 'STANDARD', 'Yangon', 'YGN', 4000, 3.000, 500, 0, 0, 'Dagon Thiri highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('Dagon Thiri Highway Drop Off', 'ROYAL', 'Yangon', 'YGN', 4000, 5.000, 500, 0, 0, 'Dagon Thiri highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('Dagon Thiri Highway Drop Off', 'COMMITMENT', 'Yangon', 'YGN', 4000, 5.000, 500, 1500, 500, 'Dagon Thiri highway drop-off', 'ACTIVE', DATE '2026-07-31'),
  ('အောင်မြေသာစံမြို့နယ်', 'STANDARD', 'Mandalay', 'MDY', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('အောင်မြေသာစံမြို့နယ်', 'ROYAL', 'Mandalay', 'MDY', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('အောင်မြေသာစံမြို့နယ်', 'COMMITMENT', 'Mandalay', 'MDY', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ချမ်းအေးသာစံမြို့နယ်', 'STANDARD', 'Mandalay', 'MDY', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ချမ်းအေးသာစံမြို့နယ်', 'ROYAL', 'Mandalay', 'MDY', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ချမ်းအေးသာစံမြို့နယ်', 'COMMITMENT', 'Mandalay', 'MDY', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('မဟာအောင်မြေမြို့နယ်', 'STANDARD', 'Mandalay', 'MDY', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('မဟာအောင်မြေမြို့နယ်', 'ROYAL', 'Mandalay', 'MDY', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('မဟာအောင်မြေမြို့နယ်', 'COMMITMENT', 'Mandalay', 'MDY', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ချမ်းမြသာစည်မြို့နယ်', 'STANDARD', 'Mandalay', 'MDY', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ချမ်းမြသာစည်မြို့နယ်', 'ROYAL', 'Mandalay', 'MDY', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ချမ်းမြသာစည်မြို့နယ်', 'COMMITMENT', 'Mandalay', 'MDY', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပြည်ကြီးတံခွန်မြို့နယ်', 'STANDARD', 'Mandalay', 'MDY', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပြည်ကြီးတံခွန်မြို့နယ်', 'ROYAL', 'Mandalay', 'MDY', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပြည်ကြီးတံခွန်မြို့နယ်', 'COMMITMENT', 'Mandalay', 'MDY', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('အမရပူရမြို့နယ်', 'STANDARD', 'Mandalay', 'MDY', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('အမရပူရမြို့နယ်', 'ROYAL', 'Mandalay', 'MDY', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('အမရပူရမြို့နယ်', 'COMMITMENT', 'Mandalay', 'MDY', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပုသိမ်ကြီးမြို့နယ်', 'STANDARD', 'Mandalay', 'MDY', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပုသိမ်ကြီးမြို့နယ်', 'ROYAL', 'Mandalay', 'MDY', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပုသိမ်ကြီးမြို့နယ်', 'COMMITMENT', 'Mandalay', 'MDY', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('Mandalay', 'STANDARD', 'Mandalay', 'MDY', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('Mandalay', 'ROYAL', 'Mandalay', 'MDY', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('Mandalay', 'COMMITMENT', 'Mandalay', 'MDY', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဇမ္ဗူသီရိမြို့နယ်', 'STANDARD', 'Nay Pyi Taw', 'NPT', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဇမ္ဗူသီရိမြို့နယ်', 'ROYAL', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဇမ္ဗူသီရိမြို့နယ်', 'COMMITMENT', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဒက္ခိဏသီရိမြို့နယ်', 'STANDARD', 'Nay Pyi Taw', 'NPT', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဒက္ခိဏသီရိမြို့နယ်', 'ROYAL', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဒက္ခိဏသီရိမြို့နယ်', 'COMMITMENT', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပုဗ္ဗသီရိမြို့နယ်', 'STANDARD', 'Nay Pyi Taw', 'NPT', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပုဗ္ဗသီရိမြို့နယ်', 'ROYAL', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပုဗ္ဗသီရိမြို့နယ်', 'COMMITMENT', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဥတ္တရသီရိမြို့နယ်', 'STANDARD', 'Nay Pyi Taw', 'NPT', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဥတ္တရသီရိမြို့နယ်', 'ROYAL', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဥတ္တရသီရိမြို့နယ်', 'COMMITMENT', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဇေယျာသီရိမြို့နယ်', 'STANDARD', 'Nay Pyi Taw', 'NPT', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဇေယျာသီရိမြို့နယ်', 'ROYAL', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ဇေယျာသီရိမြို့နယ်', 'COMMITMENT', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပျဉ်းမနားမြို့နယ်', 'STANDARD', 'Nay Pyi Taw', 'NPT', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပျဉ်းမနားမြို့နယ်', 'ROYAL', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('ပျဉ်းမနားမြို့နယ်', 'COMMITMENT', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31'),
  ('Naypyitaw', 'STANDARD', 'Nay Pyi Taw', 'NPT', 6000, 3.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('Naypyitaw', 'ROYAL', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 0, 0, '', 'ACTIVE', DATE '2026-07-31'),
  ('Naypyitaw', 'COMMITMENT', 'Nay Pyi Taw', 'NPT', 6000, 5.000, 500, 1500, 500, '', 'ACTIVE', DATE '2026-07-31')
on conflict (township, customer_tier, effective_from) do update set
  tariff_zone = excluded.tariff_zone,
  tariff_zone_code = excluded.tariff_zone_code,
  base_tariff = excluded.base_tariff,
  included_kg = excluded.included_kg,
  extra_per_kg = excluded.extra_per_kg,
  commitment_min_ways = excluded.commitment_min_ways,
  commitment_refund_per_way = excluded.commitment_refund_per_way,
  note = excluded.note,
  status = excluded.status,
  updated_at = now();

create table if not exists public.be_parcel_financial_audit_v2 (
  audit_id uuid primary key default gen_random_uuid(),
  parcel_id text not null,
  way_id text,
  previous_input_values jsonb not null default '{}'::jsonb,
  new_input_values jsonb not null default '{}'::jsonb,
  previous_calculated_values jsonb not null default '{}'::jsonb,
  new_calculated_values jsonb not null default '{}'::jsonb,
  employee_id uuid,
  authorization_employee_id uuid,
  reason text,
  calculation_version text not null,
  created_at timestamptz not null default now()
);

create index if not exists be_parcel_financial_audit_v2_parcel_idx
  on public.be_parcel_financial_audit_v2 (parcel_id, created_at desc);

create table if not exists public.be_parcel_settlement_ledger_v2 (
  ledger_id uuid primary key default gen_random_uuid(),
  parcel_id text not null,
  way_id text,
  settlement_batch_id uuid not null,
  transaction_type text not null,
  amount bigint not null,
  calculation_version text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid,
  created_at timestamptz not null default now(),
  constraint be_parcel_settlement_ledger_v2_type_check check (
    transaction_type in (
      'CUSTOMER_COLLECTION',
      'MERCHANT_ITEM_PAYABLE',
      'DELIVERY_REVENUE',
      'DELIVERY_EXCESS_CREDIT',
      'DELIVERY_SHORTFALL_DEBIT',
      'MERCHANT_ADDITIONAL_CREDIT',
      'MERCHANT_OTHER_CHARGE',
      'COMMITMENT_REFUND',
      'COMPANY_ADDITIONAL_CUSTOMER_CHARGE'
    )
  ),
  constraint be_parcel_settlement_ledger_v2_idempotent
    unique (parcel_id, settlement_batch_id, transaction_type)
);

create or replace function public.be_calculate_parcel_financial_v2(
  p_township text,
  p_customer_tier text,
  p_amount_entry_type text,
  p_item_price bigint default null,
  p_delivery_charges bigint default null,
  p_merchant_stated_total_amount bigint default null,
  p_additional_customer_charge bigint default 0,
  p_cbm_surcharge bigint default 0,
  p_other_surcharge bigint default 0,
  p_merchant_payable_charges bigint default 0,
  p_other_merchant_credits bigint default 0,
  p_actual_weight_kg numeric default 0,
  p_merchant_monthly_ways integer default 0
) returns jsonb
language plpgsql
stable
security invoker
set search_path = public, pg_temp
as $$
declare
  v_tariff public.be_parcel_tariffs_v2%rowtype;
  v_tier text := upper(btrim(coalesce(p_customer_tier, '')));
  v_type text := upper(btrim(coalesce(p_amount_entry_type, '')));
  v_messages text[] := array[]::text[];
  v_chargeable numeric(10,3);
  v_extra numeric(10,3);
  v_weight_surcharge bigint;
  v_gross bigint;
  v_commitment_refund bigint;
  v_net bigint;
  v_effective bigint;
  v_cod bigint := 0;
  v_difference bigint;
  v_direction text;
  v_adjustment bigint;
  v_merchant_final bigint;
  v_status text;
begin
  if nullif(btrim(coalesce(p_township, '')), '') is null then
    v_messages := array_append(v_messages, 'Township is required.');
  end if;
  if v_tier not in ('STANDARD','ROYAL','COMMITMENT') then
    v_messages := array_append(v_messages, 'A valid backend-resolved customer tier is required.');
  end if;
  if v_type not in (
    'ITEM_PRICE_PLUS_DECLARED_DELIVERY',
    'TOTAL_AMOUNT_INCLUDING_DELIVERY',
    'DELIVERY_CHARGE_ONLY',
    'EXACT_COLLECTION_AMOUNT',
    'ITEM_PRICE_ONLY_DELIVERY_PAID_BY_MERCHANT'
  ) then
    v_messages := array_append(v_messages, 'Invalid amount entry type.');
  end if;

  if coalesce(p_additional_customer_charge,0) < 0
     or coalesce(p_cbm_surcharge,0) < 0
     or coalesce(p_other_surcharge,0) < 0
     or coalesce(p_merchant_payable_charges,0) < 0
     or coalesce(p_other_merchant_credits,0) < 0
     or coalesce(p_actual_weight_kg,0) < 0
     or coalesce(p_merchant_monthly_ways,0) < 0
     or (p_item_price is not null and p_item_price < 0)
     or (p_delivery_charges is not null and p_delivery_charges < 0)
     or (p_merchant_stated_total_amount is not null and p_merchant_stated_total_amount < 0) then
    v_messages := array_append(v_messages, 'Financial and weight inputs must be non-negative.');
  end if;

  select * into v_tariff
  from public.be_parcel_tariffs_v2 t
  where lower(btrim(t.township)) = lower(btrim(p_township))
    and t.customer_tier = v_tier
    and t.status = 'ACTIVE'
    and t.effective_from <= current_date
    and (t.effective_to is null or t.effective_to >= current_date)
  order by t.effective_from desc
  limit 1;

  if not found then
    v_messages := array_append(v_messages, 'No exact active tariff exists for township and customer tier.');
    v_tariff.base_tariff := 0;
    v_tariff.included_kg := 0;
    v_tariff.extra_per_kg := 0;
    v_tariff.commitment_min_ways := 0;
    v_tariff.commitment_refund_per_way := 0;
  end if;

  v_chargeable := ceil(greatest(0::numeric, coalesce(p_actual_weight_kg,0)));
  v_extra := greatest(0::numeric, v_chargeable - coalesce(v_tariff.included_kg,0));
  v_weight_surcharge := ceil(v_extra * coalesce(v_tariff.extra_per_kg,0))::bigint;
  v_gross := greatest(0::bigint,
    coalesce(v_tariff.base_tariff,0)
    + v_weight_surcharge
    + coalesce(p_cbm_surcharge,0)
    + coalesce(p_other_surcharge,0));
  v_commitment_refund := case
    when v_tier = 'COMMITMENT'
      and coalesce(p_merchant_monthly_ways,0) >= coalesce(v_tariff.commitment_min_ways,0)
    then coalesce(v_tariff.commitment_refund_per_way,0)
    else 0
  end;
  v_net := greatest(0::bigint, v_gross - v_commitment_refund);

  case v_type
    when 'ITEM_PRICE_PLUS_DECLARED_DELIVERY' then
      if p_item_price is null then v_messages := array_append(v_messages, 'Item price is required.'); end if;
      if p_delivery_charges is null then v_messages := array_append(v_messages, 'Merchant-declared delivery charge is required.'); end if;
      v_effective := p_delivery_charges;
      v_cod := coalesce(p_item_price,0) + coalesce(p_delivery_charges,0) + coalesce(p_additional_customer_charge,0);
    when 'TOTAL_AMOUNT_INCLUDING_DELIVERY' then
      if p_item_price is null then v_messages := array_append(v_messages, 'Item price is required.'); end if;
      if p_merchant_stated_total_amount is null then v_messages := array_append(v_messages, 'Merchant-stated total amount is required.'); end if;
      v_cod := coalesce(p_merchant_stated_total_amount,0);
      if v_cod < coalesce(p_item_price,0) + coalesce(p_additional_customer_charge,0) then
        v_messages := array_append(v_messages, 'Merchant-stated total cannot be below item price plus additional customer charge.');
      else
        v_effective := v_cod - coalesce(p_item_price,0) - coalesce(p_additional_customer_charge,0);
      end if;
    when 'DELIVERY_CHARGE_ONLY' then
      if p_delivery_charges is null then v_messages := array_append(v_messages, 'Merchant-declared delivery charge is required.'); end if;
      v_effective := p_delivery_charges;
      v_cod := coalesce(p_delivery_charges,0) + coalesce(p_additional_customer_charge,0);
    when 'EXACT_COLLECTION_AMOUNT' then
      if p_merchant_stated_total_amount is null then v_messages := array_append(v_messages, 'Merchant-stated total amount is required.'); end if;
      v_cod := coalesce(p_merchant_stated_total_amount,0);
      v_effective := null;
    when 'ITEM_PRICE_ONLY_DELIVERY_PAID_BY_MERCHANT' then
      if p_item_price is null then v_messages := array_append(v_messages, 'Item price is required.'); end if;
      v_effective := 0;
      v_cod := coalesce(p_item_price,0) + coalesce(p_additional_customer_charge,0);
    else
      null;
  end case;

  if cardinality(v_messages) > 0 then
    v_status := 'ERROR';
    v_direction := case when v_type = 'EXACT_COLLECTION_AMOUNT' then 'BREAKDOWN_REQUIRED' else 'NO_ADJUSTMENT' end;
  elsif v_type = 'EXACT_COLLECTION_AMOUNT' then
    v_status := 'REVIEW';
    v_direction := 'BREAKDOWN_REQUIRED';
    v_messages := array['Authorized item and delivery breakdown is required before settlement.'];
  else
    v_difference := coalesce(v_effective,0) - v_net;
    v_adjustment := v_difference;
    v_direction := case when v_difference > 0 then 'CREDIT_TO_MERCHANT'
                        when v_difference < 0 then 'DEDUCT_FROM_MERCHANT'
                        else 'NO_ADJUSTMENT' end;
    v_merchant_final := coalesce(p_item_price,0) + v_difference
      + coalesce(p_other_merchant_credits,0) - coalesce(p_merchant_payable_charges,0);
    v_status := 'OK';
    v_messages := array['Ready for receiver collection and merchant settlement.'];
  end if;

  return jsonb_build_object(
    'tariff_zone', v_tariff.tariff_zone,
    'tariff_zone_code', v_tariff.tariff_zone_code,
    'base_tariff', v_tariff.base_tariff,
    'included_kg', v_tariff.included_kg,
    'extra_per_kg', v_tariff.extra_per_kg,
    'commitment_min_ways', v_tariff.commitment_min_ways,
    'commitment_refund_per_way', v_tariff.commitment_refund_per_way,
    'chargeable_weight_kg', v_chargeable,
    'extra_kg', v_extra,
    'weight_surcharge', v_weight_surcharge,
    'gross_system_delivery_charge', v_gross,
    'commitment_refund', v_commitment_refund,
    'net_system_delivery_charge', v_net,
    'effective_declared_delivery_charge', v_effective,
    'cod_amount', v_cod,
    'delivery_difference', v_difference,
    'merchant_settlement_adjustment', v_adjustment,
    'settlement_direction', v_direction,
    'merchant_final_settlement_amount', v_merchant_final,
    'validation_status', v_status,
    'validation_message', array_to_string(v_messages, ' '),
    'calculation_version', 'PARCEL_FINANCIAL_V2',
    'calculated_at', now()
  );
end
$$;

create or replace function public.be_recalculate_parcel_financial_v2(
  p_parcel_id text,
  p_actor uuid default null,
  p_authorized_by uuid default null,
  p_reason text default null
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_parcel public.parcels%rowtype;
  v_profile public.be_merchant_financial_profiles_v2%rowtype;
  v_monthly integer := 0;
  v_result jsonb;
  v_previous_input jsonb;
  v_previous_calculated jsonb;
begin
  select * into v_parcel
  from public.parcels
  where id::text = p_parcel_id
  for update;

  if not found then raise exception 'Parcel % not found', p_parcel_id; end if;
  if upper(coalesce(v_parcel.status,'')) in ('DELIVERED','SETTLED','COD_SETTLED')
     or v_parcel.financial_settled_at is not null then
    raise exception 'Delivered or settled parcel financials cannot be edited directly; create an adjustment transaction';
  end if;
  if v_parcel.financial_locked_at is not null and p_authorized_by is null then
    raise exception 'Financial recalculation after lock/printing requires authorization';
  end if;

  select * into v_profile
  from public.be_merchant_financial_profiles_v2
  where merchant_id = v_parcel.merchant_id::text
    and is_active
    and effective_from <= current_date
    and (effective_to is null or effective_to >= current_date)
  limit 1;

  if not found then
    raise exception 'No active merchant financial profile exists for merchant %', v_parcel.merchant_id;
  end if;

  select count(*)::integer into v_monthly
  from public.parcels p
  where p.merchant_id::text = v_parcel.merchant_id::text
    and date_trunc('month', coalesce(p.created_at, now())) = date_trunc('month', coalesce(v_parcel.created_at, now()))
    and upper(coalesce(p.status,'')) not in ('CANCELLED','FAILED');

  v_previous_input := jsonb_build_object(
    'item_price', v_parcel.item_price,
    'delivery_charges', v_parcel.delivery_charges,
    'weight_kg', v_parcel.weight_kg,
    'amount_entry_type', v_parcel.amount_entry_type,
    'merchant_stated_total_amount', v_parcel.merchant_stated_total_amount,
    'additional_customer_charge', v_parcel.additional_customer_charge,
    'cbm_surcharge', v_parcel.cbm_surcharge,
    'other_surcharge', v_parcel.other_surcharge,
    'merchant_payable_charges', v_parcel.merchant_payable_charges,
    'other_merchant_credits', v_parcel.other_merchant_credits
  );
  v_previous_calculated := jsonb_build_object(
    'cod_amount', v_parcel.cod_amount,
    'net_system_delivery_charge', v_parcel.net_system_delivery_charge,
    'delivery_difference', v_parcel.delivery_difference,
    'settlement_direction', v_parcel.settlement_direction,
    'merchant_final_settlement_amount', v_parcel.merchant_final_settlement_amount,
    'validation_status', v_parcel.validation_status,
    'calculation_version', v_parcel.calculation_version,
    'calculated_at', v_parcel.calculated_at
  );

  v_result := public.be_calculate_parcel_financial_v2(
    v_parcel.township::text,
    v_profile.customer_tier,
    v_parcel.amount_entry_type::text,
    v_parcel.item_price::bigint,
    v_parcel.delivery_charges::bigint,
    v_parcel.merchant_stated_total_amount::bigint,
    v_parcel.additional_customer_charge::bigint,
    v_parcel.cbm_surcharge::bigint,
    v_parcel.other_surcharge::bigint,
    v_parcel.merchant_payable_charges::bigint,
    v_parcel.other_merchant_credits::bigint,
    v_parcel.weight_kg::numeric,
    v_monthly
  );

  if v_result->>'validation_status' = 'ERROR' then
    raise exception 'Parcel financial validation failed: %', v_result->>'validation_message';
  end if;

  update public.parcels set
    customer_tier = v_profile.customer_tier,
    monthly_ways = v_monthly,
    cod_amount = (v_result->>'cod_amount')::bigint,
    tariff_zone = v_result->>'tariff_zone',
    tariff_zone_code = v_result->>'tariff_zone_code',
    base_tariff = (v_result->>'base_tariff')::bigint,
    included_kg = (v_result->>'included_kg')::numeric,
    extra_per_kg = (v_result->>'extra_per_kg')::bigint,
    commitment_min_ways = (v_result->>'commitment_min_ways')::integer,
    commitment_refund_per_way = (v_result->>'commitment_refund_per_way')::bigint,
    chargeable_weight_kg = (v_result->>'chargeable_weight_kg')::numeric,
    extra_kg = (v_result->>'extra_kg')::numeric,
    weight_surcharge = (v_result->>'weight_surcharge')::bigint,
    gross_system_delivery_charge = (v_result->>'gross_system_delivery_charge')::bigint,
    commitment_refund = (v_result->>'commitment_refund')::bigint,
    net_system_delivery_charge = (v_result->>'net_system_delivery_charge')::bigint,
    effective_declared_delivery_charge = nullif(v_result->>'effective_declared_delivery_charge','')::bigint,
    delivery_difference = nullif(v_result->>'delivery_difference','')::bigint,
    settlement_direction = v_result->>'settlement_direction',
    merchant_settlement_adjustment = nullif(v_result->>'merchant_settlement_adjustment','')::bigint,
    merchant_final_settlement_amount = nullif(v_result->>'merchant_final_settlement_amount','')::bigint,
    validation_status = v_result->>'validation_status',
    validation_message = v_result->>'validation_message',
    calculation_version = v_result->>'calculation_version',
    calculated_at = (v_result->>'calculated_at')::timestamptz,
    entered_by = coalesce(entered_by, p_actor),
    authorized_by = p_authorized_by
  where id::text = p_parcel_id;

  insert into public.be_parcel_financial_audit_v2 (
    parcel_id, way_id, previous_input_values, new_input_values,
    previous_calculated_values, new_calculated_values,
    employee_id, authorization_employee_id, reason, calculation_version
  ) values (
    p_parcel_id, v_parcel.way_id::text, v_previous_input, v_previous_input,
    v_previous_calculated, v_result,
    p_actor, p_authorized_by, p_reason, 'PARCEL_FINANCIAL_V2'
  );

  return v_result;
end
$$;

create or replace function public.be_lock_parcel_financial_v2(
  p_parcel_id text,
  p_actor uuid,
  p_reason text default 'WAYBILL_PRINTED'
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.parcels
  set financial_locked_at = coalesce(financial_locked_at, now()),
      financial_locked_by = coalesce(financial_locked_by, p_actor),
      financial_lock_reason = coalesce(financial_lock_reason, p_reason)
  where id::text = p_parcel_id;
  if not found then raise exception 'Parcel % not found', p_parcel_id; end if;
  return jsonb_build_object('ok',true,'parcel_id',p_parcel_id,'locked_at',now());
end
$$;

create or replace function public.be_settle_parcel_financial_v2(
  p_parcel_id text,
  p_settlement_batch_id uuid,
  p_actor uuid default null
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v public.parcels%rowtype;
  v_inserted integer := 0;
begin
  select * into v from public.parcels where id::text = p_parcel_id for update;
  if not found then raise exception 'Parcel % not found', p_parcel_id; end if;
  if upper(coalesce(v.status,'')) <> 'DELIVERED' then raise exception 'Parcel must be DELIVERED before settlement'; end if;
  if v.validation_status <> 'OK' then raise exception 'Parcel validation_status must be OK'; end if;
  if v.settlement_direction = 'BREAKDOWN_REQUIRED' then raise exception 'Authorized breakdown is required before settlement'; end if;
  if v.financial_settled_at is not null then
    return jsonb_build_object('ok',true,'idempotent',true,'parcel_id',p_parcel_id,'batch_id',v.financial_settlement_batch_id);
  end if;

  insert into public.be_parcel_settlement_ledger_v2
    (parcel_id, way_id, settlement_batch_id, transaction_type, amount, calculation_version, created_by)
  values
    (p_parcel_id, v.way_id::text, p_settlement_batch_id, 'CUSTOMER_COLLECTION', coalesce(v.cod_amount,0), v.calculation_version, p_actor),
    (p_parcel_id, v.way_id::text, p_settlement_batch_id, 'MERCHANT_ITEM_PAYABLE', coalesce(v.item_price,0), v.calculation_version, p_actor),
    (p_parcel_id, v.way_id::text, p_settlement_batch_id, 'DELIVERY_REVENUE', coalesce(v.gross_system_delivery_charge,0), v.calculation_version, p_actor)
  on conflict do nothing;
  get diagnostics v_inserted = row_count;

  if coalesce(v.delivery_difference,0) > 0 then
    insert into public.be_parcel_settlement_ledger_v2 values
      (gen_random_uuid(), p_parcel_id, v.way_id::text, p_settlement_batch_id, 'DELIVERY_EXCESS_CREDIT', v.delivery_difference, v.calculation_version, '{}'::jsonb, p_actor, now())
    on conflict do nothing;
  elsif coalesce(v.delivery_difference,0) < 0 then
    insert into public.be_parcel_settlement_ledger_v2 values
      (gen_random_uuid(), p_parcel_id, v.way_id::text, p_settlement_batch_id, 'DELIVERY_SHORTFALL_DEBIT', v.delivery_difference, v.calculation_version, '{}'::jsonb, p_actor, now())
    on conflict do nothing;
  end if;

  if coalesce(v.commitment_refund,0) > 0 then
    insert into public.be_parcel_settlement_ledger_v2 values
      (gen_random_uuid(), p_parcel_id, v.way_id::text, p_settlement_batch_id, 'COMMITMENT_REFUND', -v.commitment_refund, v.calculation_version, '{}'::jsonb, p_actor, now())
    on conflict do nothing;
  end if;
  if coalesce(v.other_merchant_credits,0) > 0 then
    insert into public.be_parcel_settlement_ledger_v2 values
      (gen_random_uuid(), p_parcel_id, v.way_id::text, p_settlement_batch_id, 'MERCHANT_ADDITIONAL_CREDIT', v.other_merchant_credits, v.calculation_version, '{}'::jsonb, p_actor, now())
    on conflict do nothing;
  end if;
  if coalesce(v.merchant_payable_charges,0) > 0 then
    insert into public.be_parcel_settlement_ledger_v2 values
      (gen_random_uuid(), p_parcel_id, v.way_id::text, p_settlement_batch_id, 'MERCHANT_OTHER_CHARGE', -v.merchant_payable_charges, v.calculation_version, '{}'::jsonb, p_actor, now())
    on conflict do nothing;
  end if;
  if coalesce(v.additional_customer_charge,0) > 0 then
    insert into public.be_parcel_settlement_ledger_v2 values
      (gen_random_uuid(), p_parcel_id, v.way_id::text, p_settlement_batch_id, 'COMPANY_ADDITIONAL_CUSTOMER_CHARGE', v.additional_customer_charge, v.calculation_version, '{}'::jsonb, p_actor, now())
    on conflict do nothing;
  end if;

  update public.parcels
  set financial_settlement_batch_id = p_settlement_batch_id,
      financial_settled_at = now(),
      financial_settled_by = p_actor
  where id::text = p_parcel_id;

  return jsonb_build_object('ok',true,'idempotent',false,'parcel_id',p_parcel_id,'batch_id',p_settlement_batch_id);
end
$$;

-- Constraints are NOT VALID so existing historical debt does not block installation.
do $$
begin
  if not exists (select 1 from pg_constraint where conname='parcels_amount_entry_type_check' and conrelid='public.parcels'::regclass) then
    alter table public.parcels add constraint parcels_amount_entry_type_check check (
      amount_entry_type is null or amount_entry_type in (
        'ITEM_PRICE_PLUS_DECLARED_DELIVERY','TOTAL_AMOUNT_INCLUDING_DELIVERY','DELIVERY_CHARGE_ONLY',
        'EXACT_COLLECTION_AMOUNT','ITEM_PRICE_ONLY_DELIVERY_PAID_BY_MERCHANT'
      )) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='parcels_customer_tier_check' and conrelid='public.parcels'::regclass) then
    alter table public.parcels add constraint parcels_customer_tier_check check (
      customer_tier is null or customer_tier in ('STANDARD','ROYAL','COMMITMENT')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='parcels_settlement_direction_check' and conrelid='public.parcels'::regclass) then
    alter table public.parcels add constraint parcels_settlement_direction_check check (
      settlement_direction is null or settlement_direction in ('CREDIT_TO_MERCHANT','DEDUCT_FROM_MERCHANT','NO_ADJUSTMENT','BREAKDOWN_REQUIRED')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='parcels_validation_status_check' and conrelid='public.parcels'::regclass) then
    alter table public.parcels add constraint parcels_validation_status_check check (
      validation_status is null or validation_status in ('OK','REVIEW','ERROR')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='parcels_non_negative_amounts_check' and conrelid='public.parcels'::regclass) then
    alter table public.parcels add constraint parcels_non_negative_amounts_check check (
      coalesce(item_price,0) >= 0 and coalesce(delivery_charges,0) >= 0 and coalesce(cod_amount,0) >= 0
      and coalesce(merchant_stated_total_amount,0) >= 0 and coalesce(additional_customer_charge,0) >= 0
      and coalesce(cbm_surcharge,0) >= 0 and coalesce(other_surcharge,0) >= 0
      and coalesce(merchant_payable_charges,0) >= 0 and coalesce(other_merchant_credits,0) >= 0
    ) not valid;
  end if;
end
$$;

comment on column public.parcels.delivery_charges is 'Merchant-declared receiver-facing delivery charge; never the company tariff.';
comment on column public.parcels.cod_amount is 'Server-calculated final total collected from receiver.';
comment on column public.parcels.net_system_delivery_charge is 'Stored company tariff snapshot after commitment refund.';
comment on column public.parcels.delivery_difference is 'effective_declared_delivery_charge - net_system_delivery_charge; may be negative.';
comment on function public.be_recalculate_parcel_financial_v2(text,uuid,uuid,text) is 'Server-authoritative recalculation. Ignores imported calculated values; resolves merchant tier and monthly ways from database.';

notify pgrst, 'reload schema';
commit;

select jsonb_build_object(
  'build','PARCEL_FINANCIAL_V2_BACKEND_2026-07-31',
  'tariff_rows',(select count(*) from public.be_parcel_tariffs_v2 where effective_from=DATE '2026-07-31'),
  'calculator','be_calculate_parcel_financial_v2',
  'recalculator','be_recalculate_parcel_financial_v2',
  'settlement','be_settle_parcel_financial_v2',
  'deletes_rows',false
) as parcel_financial_v2_installation;
