export const BRITIUM_TYPOGRAPHY = {
  font: 'Poppins',
  headerPx: 20,
  subheadingPx: 18,
  emphasisPx: 16,
  paragraphPx: 14,
} as const

export const BRITIUM_BACKEND_ROLE_ONLY = true

export const BRITIUM_LOGIN_BACKEND_TABLES = {
  enterpriseUserRegistry: 'be_user_account_registry',
  mobileWorkforceAccounts: 'be_mobile_workforce_accounts',
} as const

export const BRITIUM_OPERATIONAL_ID_RULES = {
  pickupId: 'P{MMDD}-{MERCHANT_CODE_3}-{PICKUP_PARCEL_COUNT_3}',
  deliverId: 'D{MMDD}-{MERCHANT_CODE_3}-{DELIVER_SEQUENCE_3}',
  invoiceNo: 'I{MMDD}-{MERCHANT_CODE_3}-{SEQUENCE_OR_BATCH_COUNT_3}',
  waybillNo: 'W{MMDD}-{MERCHANT_CODE_3}-{SEQUENCE_OR_BATCH_COUNT_3}',
  backendGeneratedOnly: true,
} as const

export const BRITIUM_PROCESS_STATUS = {
  pickup: [
    'PICKUP_REQUESTED',
    'PICKUP_ASSIGNED',
    'RIDER_EN_ROUTE_PICKUP',
    'ARRIVED_AT_PICKUP',
    'PICKUP_COMPLETED',
    'PICKUP_FAILED',
    'PICKUP_RESCHEDULED',
    'PICKUP_CANCELLED',
  ],
  warehouse: [
    'RECEIVED_AT_ORIGIN',
    'SORTING',
    'READY_FOR_DISPATCH',
    'IN_TRANSIT_TO_HUB',
    'RECEIVED_AT_DESTINATION',
    'WAREHOUSE_HOLD',
    'DAMAGED',
    'LOST',
  ],
  delivery: [
    'READY_FOR_DELIVERY',
    'DELIVERY_ASSIGNED',
    'OUT_FOR_DELIVERY',
    'DELIVERY_ATTEMPTED',
    'DELIVERED',
    'DELIVERY_FAILED',
    'DELIVERY_RESCHEDULED',
  ],
  return: ['RTO_INITIATED', 'RETURNED_TO_SENDER'],
} as const

export const BRITIUM_DATA_ENTRY_TEMPLATE_COLUMNS = [
  'row_no',
  'upload_action',
  'requester_type',
  'merchant_id',
  'merchant_code',
  'merchant_sender_name',
  'sender_phone',
  'pickup_address',
  'pickup_township',
  'pickup_city',
  'pickup_date',
  'pickup_time',
  'pickup_parcel_count',
  'weight_kg',
  'item_value',
  'pickup_id',
  'deliver_id',
  'invoice_no',
  'waybill_no',
  'recipient_name',
  'recipient_phone',
  'delivery_township',
  'delivery_address',
  'delivery_fee',
  'extra_weight_fee',
  'prepaid_amount',
  'cod_amount',
  'destination',
  'payment_method',
  'service_type',
  'priority',
  'pickup_by_1',
  'pickup_by_2',
  'remarks',
  'upload_status',
  'api_message',
  'source_row_no',
] as const

export const BRITIUM_WAREHOUSE_TEMPLATE_COLUMNS = [
  'scan_date',
  'scan_time',
  'warehouse_branch',
  'operator',
  'pickup_id',
  'deliver_id',
  'invoice_no',
  'waybill_no',
  'merchant_id',
  'merchant_code',
  'merchant_name',
  'expected_parcel_count',
  'scanned_parcel_count',
  'remaining_count',
  'tracking_no',
  'scan_type',
  'current_status',
  'next_status',
  'bag_code',
  'bag_destination',
  'route_zone',
  'exception_reason',
  'damage_note',
  'missing_parcel_note',
  'validation_status',
  'api_message',
] as const

export const BRITIUM_REQUIRED_BACKEND_OBJECTS = {
  masterData: 'be_master_data_options',
  pickupRequests: 'be_portal_pickup_requests',
  pickupIdReservations: 'be_pickup_id_reservations',
  notifications: 'be_app_notifications',
  cargoEvents: 'be_portal_cargo_events',
  customerServiceThreads: 'be_portal_service_threads',
  customerServiceMessages: 'be_portal_service_messages',
  workforce: 'be_mobile_workforce_accounts',
  userRegistry: 'be_user_account_registry',
  branchNodes: 'be_branch_nodes',
  tariffMaster: 'be_tariff_master',
  auditArchive: 'be_go_live_archived_operational_test_data',
  resetLog: 'be_go_live_runtime_reset_log',
} as const

export const BRITIUM_REQUIRED_RPC = {
  resolveUserAccess: ['be_resolve_user_access_by_email', 'be_get_user_access_by_email'],
  liveDispatchBoard: 'be_get_live_dispatch_wayplan_board',
  pickupOptions: 'be_get_pickup_order_options',
  operationalMasterdata: 'be_get_operational_masterdata',
  templateSyncRow: 'be_template_sync_row',
  workflowEventStrict: 'be_logistics_apply_workflow_event_strict',
  assignWayplan: 'be_assign_live_dispatch_wayplan',
  tariffCalculator: 'be_calculate_delivery_charge',
  reportCatalog: 'be_get_report_catalog',
  reportDownload: 'be_get_report_download_data',
} as const
