-- ============================================================
-- Britium Express CS-first workflow schema patch
-- Safe patch for pages generated by ChatGPT
-- Run once before deploying the TSX pages.
-- ============================================================

create extension if not exists pgcrypto;

alter table public.be_portal_pickup_requests
  add column if not exists requested_pickup_date date,
  add column if not exists requested_pickup_time_window text,
  add column if not exists cs_notes text,
  add column if not exists total_items int default 0,
  add column if not exists total_parcels int default 0,
  add column if not exists supervisor_assigned_at timestamptz,
  add column if not exists pickup_completed_at timestamptz,
  add column if not exists warehouse_ready_at timestamptz,
  add column if not exists delivery_wayplan_id uuid,
  add column if not exists warehouse_location text;

create table if not exists public.be_portal_pickup_request_items (
  item_id uuid primary key default gen_random_uuid(),
  pickup_request_id uuid not null references public.be_portal_pickup_requests(id) on delete cascade,
  pickup_id text not null,
  item_no int not null default 1,
  recipient_name text,
  recipient_phone text,
  delivery_address text,
  delivery_township text,
  delivery_city text default 'Yangon',
  parcel_count int default 1,
  weight_kg numeric default 0,
  cod_amount numeric default 0,
  delivery_fee numeric default 0,
  item_description text,
  special_instruction text,
  priority text default 'NORMAL',
  item_status text not null default 'SUBMITTED',
  assigned_delivery_worker_code text,
  assigned_delivery_worker_name text,
  wayplan_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (pickup_id, item_no)
);

create index if not exists idx_pickup_request_items_pickup_id on public.be_portal_pickup_request_items(pickup_id);
create index if not exists idx_pickup_request_items_status on public.be_portal_pickup_request_items(item_status);
create index if not exists idx_pickup_request_items_township on public.be_portal_pickup_request_items(delivery_township);

create table if not exists public.be_delivery_wayplans (
  wayplan_id uuid primary key default gen_random_uuid(),
  wayplan_no text unique not null,
  branch_code text default 'YGN',
  warehouse_location text,
  planned_delivery_date date not null default current_date,
  status text not null default 'DRAFT',
  generated_by uuid,
  reviewed_by uuid,
  reviewed_at timestamptz,
  confirmed_by uuid,
  confirmed_at timestamptz,
  supervisor_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.be_delivery_wayplan_items (
  id uuid primary key default gen_random_uuid(),
  wayplan_id uuid not null references public.be_delivery_wayplans(wayplan_id) on delete cascade,
  pickup_request_id uuid not null,
  pickup_item_id uuid not null,
  pickup_id text not null,
  delivery_township text,
  delivery_zone text,
  proposed_sequence int,
  final_sequence int,
  proposed_worker_code text,
  final_worker_code text,
  final_worker_name text,
  include_in_wayplan boolean default true,
  supervisor_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (wayplan_id, pickup_item_id)
);

create index if not exists idx_delivery_wayplans_status on public.be_delivery_wayplans(status);
create index if not exists idx_delivery_wayplan_items_wayplan on public.be_delivery_wayplan_items(wayplan_id);
create index if not exists idx_delivery_wayplan_items_pickup on public.be_delivery_wayplan_items(pickup_id);

grant select, insert, update on public.be_portal_pickup_request_items to authenticated;
grant select, insert, update on public.be_delivery_wayplans to authenticated;
grant select, insert, update on public.be_delivery_wayplan_items to authenticated;

notify pgrst, 'reload schema';
