import fs from 'node:fs';import path from 'node:path';
const BUILD='PORTAL_DATA_ENTRY_MERCHANT_DELIVERY_CREDIT_V61_2_1_DIST_VERIFY_2026_08_02';const root=path.resolve(process.argv[2]||'.');const dist=path.join(root,'dist');
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const f=path.join(dir,e.name);return e.isDirectory()?walk(f):/\.(js|mjs|css|html)$/i.test(e.name)?[f]:[];});}
if(!fs.existsSync(dist)){console.error(JSON.stringify({ok:false,build:BUILD,root,message:'dist directory is missing',deploy_performed:false},null,2));process.exit(1);}
const files=walk(dist);const content=files.map(f=>fs.readFileSync(f,'utf8')).join('\n');
const required=['PORTAL_DATA_ENTRY_FINANCIAL_V2_MERCHANT_DELIVERY_CREDIT_V61_2_1_2026_08_02','PORTAL_TOWNSHIP_TARIFF_DIRECTORY_V61_2_1_2026_08_02','data-merchant-delivery-difference-credit','Merchant credit from delivery difference','ပို့ဆောင်ခကွာဟချက်အရ လုပ်ငန်းရှင်ရရန်ငွေ','အပေါင်းတန်ဖိုးဖြစ်သော ပို့ဆောင်ခကွာဟချက်ကို ဗဟိုစနစ်က လုပ်ငန်းရှင်သို့ ပေးရန်ငွေအဖြစ်','merchant_settlement_adjustment','merchant_final_settlement_amount','MUTATION_SHADOW','MMR013019'];
const forbidden=['BRITIUM GO-LIVE UAT','other_merchant_credits = delivery_difference','additional_customer_charge = delivery_difference'];
const missing=required.filter(m=>!content.includes(m));const forbiddenFound=forbidden.filter(m=>content.includes(m));const townshipCodeCount=new Set(content.match(/MMR\d{6}/g)||[]).size;if(townshipCodeCount<350)missing.push(`township-code-count:${townshipCodeCount}`);
const result={ok:missing.length===0&&forbiddenFound.length===0,build:BUILD,root,scanned_files:files.length,required_markers_present:required.length-missing.filter(x=>!x.startsWith('township-code-count:')).length,required_markers_total:required.length,unique_township_codes_found:townshipCodeCount,positive_delivery_difference_credit_ui_present:content.includes('Merchant credit from delivery difference'),duplicate_credit_prevention_present:content.includes('ဖောက်သည်ထံမှ ထပ်ဆောင်းကောက်ခံငွေ သို့မဟုတ် လုပ်ငန်းရှင်ရရန်ရှိ အခြားငွေများအကွက်ထဲ ထပ်မထည့်ရပါ'),missing,forbidden_found:forbiddenFound,financial_writes_enabled_by_verifier:false,deploy_performed:false};console.log(JSON.stringify(result,null,2));if(!result.ok)process.exit(1);
