import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, CheckCircle2, RefreshCw, ShieldCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

export const PRODUCTION_READINESS_BUILD =
  "PRODUCTION_READINESS_NO_UAT_V56_2026_07_31";

type Check = {
  key: string;
  label: string;
  status: "PASS" | "WARNING" | "FAIL" | "PENDING";
  detail: string;
};

const CHECKS: Array<{ key: string; label: string }> = [
  { key: "master", label: "Master Data" },
  { key: "runtime", label: "Production Runtime" },
  { key: "pickup", label: "Pickup Workflow" },
  { key: "dispatch", label: "Dispatch" },
  { key: "warehouse", label: "Warehouse" },
  { key: "branch", label: "Branches" },
  { key: "finance", label: "Finance and Settlement" },
  { key: "lineage", label: "Canonical Way/Pickup Lineage" },
];

export default function ProductionReadinessPage() {
  const [checks, setChecks] = useState<Check[]>(
    CHECKS.map((item) => ({ ...item, status: "PENDING", detail: "Waiting for the production readiness RPC." })),
  );
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    setError("");
    try {
      const { data, error: rpcError } = await (supabase as any).rpc("be_go_live_readiness_snapshot");
      if (rpcError) throw rpcError;
      const source = data?.checks || {};
      const summary = data?.summary || {};
      setChecks(
        CHECKS.map((item) => {
          const row = source[item.key] || {};
          const raw = String(row.status || (summary[item.key] === true ? "PASS" : "WARNING")).toUpperCase();
          const status: Check["status"] = ["PASS", "WARNING", "FAIL"].includes(raw) ? (raw as Check["status"]) : "WARNING";
          return {
            ...item,
            status,
            detail: String(row.detail || row.message || `Backend returned ${status.toLowerCase()} for ${item.label}.`),
          };
        }),
      );
      setGeneratedAt(data?.generated_at || new Date().toISOString());
    } catch (loadError: any) {
      const message = loadError?.message || "Production readiness snapshot is unavailable.";
      setChecks(CHECKS.map((item) => ({ ...item, status: "FAIL", detail: message })));
      setError(message);
      setGeneratedAt(null);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void load();
  }, []);

  const totals = useMemo(
    () => ({
      pass: checks.filter((item) => item.status === "PASS").length,
      warning: checks.filter((item) => item.status === "WARNING").length,
      fail: checks.filter((item) => item.status === "FAIL").length,
      pending: checks.filter((item) => item.status === "PENDING").length,
    }),
    [checks],
  );

  return (
    <main className="space-y-5" data-build={PRODUCTION_READINESS_BUILD}>
      <section className="rounded-3xl border border-[#1a3a5c] bg-[#0b2236] p-6">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-[11px] font-black uppercase tracking-[0.22em] text-[#f6b84b]">
              <ShieldCheck size={15} /> Production Health
            </div>
            <h1 className="mt-2 text-3xl font-black text-[#eef8ff]">Britium Production Readiness</h1>
            <p className="mt-2 max-w-4xl text-[13px] leading-6 text-[#8fb4d0]">
              Read-only readiness status from <code>be_go_live_readiness_snapshot</code>. No sample rows, local pass states, or cleanup mutations are generated by this page.
            </p>
          </div>
          <button
            type="button"
            onClick={() => void load()}
            disabled={loading}
            className="inline-flex items-center gap-2 rounded-xl bg-[#f6b84b] px-4 py-2.5 text-[12px] font-black text-[#061524] disabled:opacity-50"
          >
            <RefreshCw size={15} className={loading ? "animate-spin" : ""} />
            Refresh Health
          </button>
        </div>
        {error ? (
          <div className="mt-4 flex items-start gap-2 rounded-xl border border-rose-600/40 bg-rose-900/20 p-3 text-[12px] text-rose-200">
            <AlertTriangle size={15} className="mt-0.5 shrink-0" /> {error}
          </div>
        ) : null}
        <div className="mt-4 text-[11px] text-[#6f98b8]">Generated: {formatDate(generatedAt)}</div>
      </section>

      <section className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <Metric label="Passed" value={totals.pass} tone="text-emerald-300" />
        <Metric label="Warnings" value={totals.warning} tone="text-amber-300" />
        <Metric label="Failed" value={totals.fail} tone="text-rose-300" />
        <Metric label="Pending" value={totals.pending} tone="text-[#8fb4d0]" />
      </section>

      <section className="rounded-3xl border border-[#1a3a5c] bg-[#0b2236] p-5">
        <div className="mb-4 flex items-center gap-2 text-[14px] font-black uppercase tracking-widest text-[#eef8ff]">
          <Activity size={17} className="text-[#f6b84b]" /> Production Checks
        </div>
        <div className="grid gap-3 md:grid-cols-2">
          {checks.map((check) => (
            <article key={check.key} className="rounded-2xl border border-[#1a3a5c] bg-[#081b2e] p-4">
              <div className="flex items-start justify-between gap-3">
                <div className="font-black text-[#eef8ff]">{check.label}</div>
                <Status value={check.status} />
              </div>
              <p className="mt-2 text-[12px] leading-5 text-[#8fb4d0]">{check.detail}</p>
            </article>
          ))}
        </div>
      </section>
    </main>
  );
}

function Metric({ label, value, tone }: { label: string; value: number; tone: string }) {
  return (
    <div className="rounded-2xl border border-[#1a3a5c] bg-[#0b2236] p-4">
      <div className="text-[10px] font-black uppercase tracking-widest text-[#6f98b8]">{label}</div>
      <div className={`mt-2 text-3xl font-black ${tone}`}>{value}</div>
    </div>
  );
}

function Status({ value }: { value: Check["status"] }) {
  const tone = value === "PASS"
    ? "border-emerald-600/40 bg-emerald-900/20 text-emerald-300"
    : value === "FAIL"
      ? "border-rose-600/40 bg-rose-900/20 text-rose-300"
      : value === "WARNING"
        ? "border-amber-600/40 bg-amber-900/20 text-amber-300"
        : "border-slate-600/40 bg-slate-900/20 text-slate-300";
  return (
    <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[9px] font-black ${tone}`}>
      {value === "PASS" ? <CheckCircle2 size={11} /> : null}{value}
    </span>
  );
}

function formatDate(value?: string | null) {
  if (!value) return "Not available";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString();
}
