import { bilingualAddressQueries, convertMyanmarAddressToEnglish } from "@/lib/myanmarAddressConverter";
import { resolvePostalCode, type PostalMatch } from "@/lib/postalCodeResolver";
export type DeliveryLocation={deliveryWayId:string;latitude:number;longitude:number;label:string;originalAddress:string;englishAddress:string;township:string;postalCode?:string;postalMatchLevel?:PostalMatch["matchLevel"];matchLevel:"ADDRESS_EXACT"|"POI_EXACT"|"STREET_APPROXIMATE"|"WARD_APPROXIMATE"|"MANUAL";confidence:number;coordinateSource:string;reviewStatus:"ACCEPTED"|"MANUAL_REVIEW"};
const accessToken=()=>String(import.meta.env.VITE_MAPBOX_ACCESS_TOKEN||import.meta.env.VITE_MAPBOX_TOKEN||"").trim();
export function validMyanmarCoordinate(lng:unknown,lat:unknown){const longitude=Number(lng),latitude=Number(lat);return Number.isFinite(longitude)&&Number.isFinite(latitude)&&latitude>=9&&latitude<=29&&longitude>=92&&longitude<=102&&!(latitude===0&&longitude===0)}
function parseCoordinate(value:string){const match=value.match(/(-?\d{1,3}(?:\.\d+)?)\s*[, ]\s*(-?\d{1,3}(?:\.\d+)?)/);if(!match)return null;const a=Number(match[1]),b=Number(match[2]);if(validMyanmarCoordinate(b,a))return{latitude:a,longitude:b};if(validMyanmarCoordinate(a,b))return{latitude:b,longitude:a};return null}
function featureType(feature:any){return String(feature?.properties?.feature_type||feature?.place_type?.[0]||feature?.type||"").toLowerCase()}
function classify(feature:any){const type=featureType(feature);if(type==="address")return{matchLevel:"ADDRESS_EXACT" as const,confidence:.96};if(type==="poi")return{matchLevel:"POI_EXACT" as const,confidence:.9};if(type==="street")return{matchLevel:"STREET_APPROXIMATE" as const,confidence:.78};if(["neighborhood","locality"].includes(type))return{matchLevel:"WARD_APPROXIMATE" as const,confidence:.67};return null}
function point(feature:any){const coordinates=feature?.geometry?.coordinates||(feature?.properties?.coordinates&&[feature.properties.coordinates.longitude,feature.properties.coordinates.latitude]);if(!Array.isArray(coordinates)||!validMyanmarCoordinate(coordinates[0],coordinates[1]))return null;return{longitude:Number(coordinates[0]),latitude:Number(coordinates[1])}}
function stripHouseNumber(value:string){return value.replace(/(?:^|,|\s)(?:house\s*)?no\.?\s*[-/#()a-z0-9]+/ig," ").replace(/\s+/g," ").trim()}
async function geocode(query:string){const token=accessToken();if(!token)throw new Error("Mapbox access token is not configured.");const url="https://api.mapbox.com/search/geocode/v6/forward?q="+encodeURIComponent(query)+"&country=MM&limit=5&language=en&access_token="+encodeURIComponent(token);const response=await fetch(url);if(!response.ok)throw new Error(`Mapbox location search failed (${response.status}).`);const data=await response.json();for(const feature of data?.features||[]){const classification=classify(feature),coordinate=point(feature);if(classification&&coordinate)return{feature,...classification,...coordinate}}return null}
export async function resolveDeliveryLocation(input:{deliveryWayId:string;address:string;township:string}){const originalAddress=String(input.address||"").trim(),direct=parseCoordinate(originalAddress),postal=resolvePostalCode(originalAddress,input.township),englishAddress=convertMyanmarAddressToEnglish(originalAddress,input.township);if(direct)return{deliveryWayId:input.deliveryWayId,...direct,label:originalAddress,originalAddress,englishAddress,township:input.township,postalCode:postal.postalCode,postalMatchLevel:postal.matchLevel,matchLevel:"MANUAL" as const,confidence:1,coordinateSource:"PASTED_VERIFIED_COORDINATE",reviewStatus:"ACCEPTED" as const};const suffix=[postal.postalCode,"Myanmar"].filter(Boolean).join(", ");const queries=[...bilingualAddressQueries(originalAddress,input.township),englishAddress].flatMap((query)=>[`${query}${suffix?`, ${suffix}`:""}`,`${stripHouseNumber(query)}${suffix?`, ${suffix}`:""}`]).filter((query,index,list)=>query.length>=5&&list.indexOf(query)===index);for(const query of queries){const result=await geocode(query);if(!result)continue;const label=result.feature?.properties?.full_address||result.feature?.properties?.name||result.feature?.place_name||query;return{deliveryWayId:input.deliveryWayId,latitude:result.latitude,longitude:result.longitude,label,originalAddress,englishAddress,township:input.township,postalCode:postal.postalCode,postalMatchLevel:postal.matchLevel,matchLevel:result.matchLevel,confidence:result.confidence,coordinateSource:`MAPBOX_AUTO_${result.matchLevel}`,reviewStatus:"ACCEPTED" as const}}return null}
export async function saveDeliveryLocation(client:any,location:DeliveryLocation){const{data,error}=await client.rpc("be_delivery_location_upsert_v11",{p_payload:{delivery_way_id:location.deliveryWayId,address_original:location.originalAddress,address_english:location.englishAddress,township:location.township,postal_code:location.postalCode||"",postal_match_level:location.postalMatchLevel||"UNRESOLVED",latitude:location.latitude,longitude:location.longitude,provider_label:location.label,match_level:location.matchLevel,confidence:location.confidence,coordinate_source:location.coordinateSource,review_status:location.reviewStatus}});if(error)throw error;return data?.location||data}
export function mapboxStaticLocationUrl(location:Pick<DeliveryLocation,"longitude"|"latitude">,zoom=15){const token=accessToken();if(!token||!validMyanmarCoordinate(location.longitude,location.latitude))return"";const lng=Number(location.longitude).toFixed(6),lat=Number(location.latitude).toFixed(6);return`https://api.mapbox.com/styles/v1/mapbox/streets-v12/static/pin-l+f59e0b(${lng},${lat})/${lng},${lat},${zoom},0/900x420@2x?access_token=${encodeURIComponent(token)}`}
