import { bilingualAddressQueries, convertMyanmarAddressToEnglish } from "@/lib/myanmarAddressConverter";
import { resolvePostalCode, type PostalMatch } from "@/lib/postalCodeResolver";
// BRITIUM_MAPBOX_SAME_ORIGIN_PROXY_V11_2
export type DeliveryLocation={deliveryWayId:string;latitude:number;longitude:number;label:string;originalAddress:string;englishAddress:string;township:string;postalCode?:string;postalMatchLevel?:PostalMatch["matchLevel"];matchLevel:"ADDRESS_EXACT"|"POI_EXACT"|"STREET_APPROXIMATE"|"WARD_APPROXIMATE"|"MANUAL";confidence:number;coordinateSource:string;reviewStatus:"ACCEPTED"|"MANUAL_REVIEW"};
const accessToken=()=>String(import.meta.env.VITE_MAPBOX_ACCESS_TOKEN||import.meta.env.VITE_MAPBOX_TOKEN||"").trim();
export function validMyanmarCoordinate(lng:unknown,lat:unknown){const longitude=Number(lng),latitude=Number(lat);return Number.isFinite(longitude)&&Number.isFinite(latitude)&&latitude>=9&&latitude<=29&&longitude>=92&&longitude<=102&&!(latitude===0&&longitude===0)}
function parseCoordinate(value:string){const match=value.match(/(-?\d{1,3}(?:\.\d+)?)\s*[, ]\s*(-?\d{1,3}(?:\.\d+)?)/);if(!match)return null;const a=Number(match[1]),b=Number(match[2]);if(validMyanmarCoordinate(b,a))return{latitude:a,longitude:b};if(validMyanmarCoordinate(a,b))return{latitude:b,longitude:a};return null}
function featureType(feature:any){return String(feature?.properties?.feature_type||feature?.place_type?.[0]||feature?.type||"").toLowerCase()}
function classify(feature:any){const type=featureType(feature);if(type==="address")return{matchLevel:"ADDRESS_EXACT" as const,confidence:.96};if(type==="poi")return{matchLevel:"POI_EXACT" as const,confidence:.9};if(type==="street")return{matchLevel:"STREET_APPROXIMATE" as const,confidence:.78};if(["neighborhood","locality"].includes(type))return{matchLevel:"WARD_APPROXIMATE" as const,confidence:.67};return null}
function point(feature:any){const coordinates=feature?.geometry?.coordinates||(feature?.properties?.coordinates&&[feature.properties.coordinates.longitude,feature.properties.coordinates.latitude]);if(!Array.isArray(coordinates)||!validMyanmarCoordinate(coordinates[0],coordinates[1]))return null;return{longitude:Number(coordinates[0]),latitude:Number(coordinates[1])}}
function stripHouseNumber(value:string){return value.replace(/(?:^|,|\s)(?:house\s*)?no\.?\s*[-/#()a-z0-9]+/ig," ").replace(/\s+/g," ").trim()}
function intersectionRoads(value:string){const cleaned=stripHouseNumber(value);const match=cleaned.match(/(?:corner\s+(?:of\s+)?|junction\s+(?:of\s+)?|intersection\s+(?:of\s+)?)([^,;]+?)\s+(?:and|&)\s+([^,;]+?)(?=,|$)/i);return match?[match[1].trim(),match[2].trim()] as const:null}
export function buildDeliveryAddressQueries(address:string,township:string,postalCode=""){const english=convertMyanmarAddressToEnglish(address,township),locality=[township,"Yangon",postalCode,"Myanmar"].filter(Boolean).join(", "),queries:string[]=[];const add=(query:string)=>{const cleaned=query.replace(/\s+/g," ").replace(/\s*,\s*/g,", ").trim();if(cleaned.length>=5&&!queries.includes(cleaned))queries.push(cleaned)};const roads=intersectionRoads(english);if(roads){const[a,b]=roads;add(`${a} & ${b}, ${locality}`);add(`${b} & ${a}, ${locality}`);add(`Junction of ${a} and ${b}, ${locality}`);add(`${a}, ${locality}`);add(`${b}, ${locality}`)}for(const query of [...bilingualAddressQueries(address,township),english]){add(`${query}, ${[postalCode,"Myanmar"].filter(Boolean).join(", ")}`);add(`${stripHouseNumber(query)}, ${[postalCode,"Myanmar"].filter(Boolean).join(", ")}`)}return queries}
function featureText(feature:any){return[feature?.properties?.full_address,feature?.properties?.name,feature?.place_name,feature?.text,...(Array.isArray(feature?.context)?feature.context.map((item:any)=>item?.text||item?.text_en):[])].filter(Boolean).join(" ").toLowerCase()}
function localityScore(feature:any,township:string){const expected=String(township||"").toLowerCase().replace(/township/g,"").trim();if(!expected)return 0;const words=expected.split(/[^a-z0-9]+/).filter((word)=>word.length>=3),text=featureText(feature),hits=words.filter((word)=>text.includes(word)).length;return hits?Math.min(.12,hits*.04):-.35}
async function geocode(query:string,township:string){const parameters=new URLSearchParams({q:query});let response:Response;try{response=await fetch(`/api/mapbox-geocode?${parameters.toString()}`,{headers:{Accept:"application/json"}})}catch{throw new Error("The Britium location service could not be reached. Check the deployment and internet connection.")}if(!response.ok){let detail="";try{const payload=await response.json();detail=String(payload?.error||payload?.message||"")}catch{}throw new Error(detail||`Britium location service failed (${response.status}).`)}const data=await response.json();let best:any=null;for(const feature of data?.features||[]){const classification=classify(feature),coordinate=point(feature);if(!classification||!coordinate)continue;const score=classification.confidence+localityScore(feature,township);if(!best||score>best.score)best={feature,...classification,...coordinate,score}}return best}
export async function resolveDeliveryLocation(input:{deliveryWayId:string;address:string;township:string}){const originalAddress=String(input.address||"").trim(),direct=parseCoordinate(originalAddress),postal=resolvePostalCode(originalAddress,input.township),englishAddress=convertMyanmarAddressToEnglish(originalAddress,input.township);if(direct)return{deliveryWayId:input.deliveryWayId,...direct,label:originalAddress,originalAddress,englishAddress,township:input.township,postalCode:postal.postalCode,postalMatchLevel:postal.matchLevel,matchLevel:"MANUAL" as const,confidence:1,coordinateSource:"PASTED_VERIFIED_COORDINATE",reviewStatus:"ACCEPTED" as const};const queries=buildDeliveryAddressQueries(originalAddress,input.township,postal.postalCode);let best:any=null;for(const query of queries){const result=await geocode(query,input.township);if(result&&(!best||result.score>best.score))best={...result,query};if(best?.score>=1.04)break}if(!best)return null;const label=best.feature?.properties?.full_address||best.feature?.properties?.name||best.feature?.place_name||best.query;return{deliveryWayId:input.deliveryWayId,latitude:best.latitude,longitude:best.longitude,label,originalAddress,englishAddress,township:input.township,postalCode:postal.postalCode,postalMatchLevel:postal.matchLevel,matchLevel:best.matchLevel,confidence:Math.max(.5,Math.min(1,best.score)),coordinateSource:`MAPBOX_AUTO_${best.matchLevel}`,reviewStatus:"ACCEPTED" as const}}
export async function saveDeliveryLocation(client:any,location:DeliveryLocation){const{data,error}=await client.rpc("be_delivery_location_upsert_v11",{p_payload:{delivery_way_id:location.deliveryWayId,address_original:location.originalAddress,address_english:location.englishAddress,township:location.township,postal_code:location.postalCode||"",postal_match_level:location.postalMatchLevel||"UNRESOLVED",latitude:location.latitude,longitude:location.longitude,provider_label:location.label,match_level:location.matchLevel,confidence:location.confidence,coordinate_source:location.coordinateSource,review_status:location.reviewStatus}});if(error)throw error;return data?.location||data}
export function mapboxStaticLocationUrl(location:Pick<DeliveryLocation,"longitude"|"latitude">,zoom=15){const token=accessToken();if(!token||!validMyanmarCoordinate(location.longitude,location.latitude))return"";const lng=Number(location.longitude).toFixed(6),lat=Number(location.latitude).toFixed(6);return`https://api.mapbox.com/styles/v1/mapbox/streets-v12/static/pin-l+f59e0b(${lng},${lat})/${lng},${lat},${zoom},0/900x420@2x?access_token=${encodeURIComponent(token)}`}

