import { bilingualAddressQueries, convertMyanmarAddressToEnglish, normalizeEnglishAddressForGeocoding } from "@/lib/myanmarAddressConverter";
import { resolvePostalCode, type PostalMatch } from "@/lib/postalCodeResolver";
// BRITIUM_MAPBOX_SAME_ORIGIN_PROXY_V11_2
export type DeliveryLocation={deliveryWayId:string;latitude:number;longitude:number;label:string;originalAddress:string;englishAddress:string;township:string;postalCode?:string;postalMatchLevel?:PostalMatch["matchLevel"];matchLevel:"ADDRESS_EXACT"|"POI_EXACT"|"STREET_APPROXIMATE"|"WARD_APPROXIMATE"|"MANUAL";confidence:number;coordinateSource:string;reviewStatus:"ACCEPTED"|"MANUAL_REVIEW"};
const accessToken=()=>String(import.meta.env.VITE_MAPBOX_ACCESS_TOKEN||import.meta.env.VITE_MAPBOX_TOKEN||"").trim();
const googleKey=()=>String(import.meta.env.VITE_GOOGLE_MAPS_API_KEY||"").trim();
export function validMyanmarCoordinate(lng:unknown,lat:unknown){const longitude=Number(lng),latitude=Number(lat);return Number.isFinite(longitude)&&Number.isFinite(latitude)&&latitude>=9&&latitude<=29&&longitude>=92&&longitude<=102&&!(latitude===0&&longitude===0)}
function parseCoordinate(value:string){const match=value.match(/(-?\d{1,3}(?:\.\d+)?)\s*[, ]\s*(-?\d{1,3}(?:\.\d+)?)/);if(!match)return null;const a=Number(match[1]),b=Number(match[2]);if(validMyanmarCoordinate(b,a))return{latitude:a,longitude:b};if(validMyanmarCoordinate(a,b))return{latitude:b,longitude:a};return null}
function featureType(feature:any){return String(feature?.properties?.feature_type||feature?.place_type?.[0]||feature?.type||"").toLowerCase()}
function classify(feature:any){const type=featureType(feature);if(type==="address")return{matchLevel:"ADDRESS_EXACT" as const,confidence:.96};if(type==="poi")return{matchLevel:"POI_EXACT" as const,confidence:.9};if(type==="street")return{matchLevel:"STREET_APPROXIMATE" as const,confidence:.78};if(["neighborhood","locality"].includes(type))return{matchLevel:"WARD_APPROXIMATE" as const,confidence:.67};return null}
function point(feature:any){const coordinates=feature?.geometry?.coordinates||(feature?.properties?.coordinates&&[feature.properties.coordinates.longitude,feature.properties.coordinates.latitude]);if(!Array.isArray(coordinates)||!validMyanmarCoordinate(coordinates[0],coordinates[1]))return null;return{longitude:Number(coordinates[0]),latitude:Number(coordinates[1])}}
function stripHouseNumber(value:string){return value.replace(/(?:^|,|\s)(?:house\s*)?no\.?\s*[-/#()a-z0-9]+/ig," ").replace(/\s+/g," ").trim()}
function intersectionRoads(value:string){const cleaned=stripHouseNumber(value);const match=cleaned.match(/(?:corner\s+(?:of\s+)?|junction\s+(?:of\s+)?|intersection\s+(?:of\s+)?)([^,;]+?)\s+(?:and|&)\s+([^,;]+?)(?=,|$)/i);return match?[match[1].trim(),match[2].trim()] as const:null}
export function buildDeliveryAddressQueries(address:string,township:string,postalCode="",quarter=""){const english=normalizeEnglishAddressForGeocoding(convertMyanmarAddressToEnglish(address,township)),locality=[quarter,township,"Yangon",postalCode,"Myanmar"].filter(Boolean).join(", "),queries:string[]=[];const add=(query:string)=>{const cleaned=normalizeEnglishAddressForGeocoding(query).replace(/\s+/g," ").replace(/\s*,\s*/g,", ").trim();if(cleaned.length>=5&&!queries.includes(cleaned))queries.push(cleaned)};const roads=intersectionRoads(english);if(roads){const[a,b]=roads;add(`${a} & ${b}, ${locality}`);add(`${b} & ${a}, ${locality}`);add(`Junction of ${a} and ${b}, ${locality}`);add(`${a}, ${locality}`);add(`${b}, ${locality}`)}for(const query of [...bilingualAddressQueries(address,township),english]){add(`${query}, ${locality}`);add(`${stripHouseNumber(query)}, ${locality}`)}return queries}
function featureText(feature:any){return[feature?.properties?.full_address,feature?.properties?.name,feature?.place_name,feature?.text,...(Array.isArray(feature?.context)?feature.context.map((item:any)=>item?.text||item?.text_en):[])].filter(Boolean).join(" ").toLowerCase()}
function localityScore(feature:any,township:string){const expected=String(township||"").toLowerCase().replace(/township/g,"").trim();if(!expected)return 0;const words=expected.split(/[^a-z0-9]+/).filter((word)=>word.length>=3),text=featureText(feature),hits=words.filter((word)=>text.includes(word)).length;return hits?Math.min(.12,hits*.04):-.35}
async function geocode(query:string,township:string){const parameters=new URLSearchParams({q:query});let response:Response;try{response=await fetch(`/api/mapbox-geocode?${parameters.toString()}`,{headers:{Accept:"application/json"}})}catch{throw new Error("The Britium location service could not be reached. Check the deployment and internet connection.")}if(!response.ok){let detail="";try{const payload=await response.json();detail=String(payload?.error||payload?.message||"")}catch{}throw new Error(detail||`Britium location service failed (${response.status}).`)}const data=await response.json();let best:any=null;for(const feature of data?.features||[]){const classification=classify(feature),coordinate=point(feature);if(!classification||!coordinate)continue;const score=classification.confidence+localityScore(feature,township);if(!best||score>best.score)best={feature,...classification,...coordinate,score}}return best}

let googleLoader:Promise<any>|null=null;
function loadGoogleMaps(){const existing=(globalThis as any).google?.maps;if(existing)return Promise.resolve(existing);if(!googleKey())return Promise.resolve(null);if(googleLoader)return googleLoader;googleLoader=new Promise((resolve,reject)=>{const callback=`__britiumGoogleMapsReady${Date.now()}`;(globalThis as any)[callback]=()=>{delete(globalThis as any)[callback];resolve((globalThis as any).google?.maps||null)};const script=document.createElement("script");script.async=true;script.defer=true;script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(googleKey())}&v=weekly&loading=async&callback=${callback}`;script.onerror=()=>{delete(globalThis as any)[callback];googleLoader=null;reject(new Error("Google Maps could not be loaded."))};document.head.appendChild(script)});return googleLoader}
function googleClassification(result:any){const types:string[]=result?.types||[];if(types.some((type)=>["street_address","premise","subpremise"].includes(type)))return{matchLevel:"ADDRESS_EXACT" as const,confidence:.97};if(types.some((type)=>["establishment","point_of_interest"].includes(type)))return{matchLevel:"POI_EXACT" as const,confidence:.91};if(types.includes("route"))return{matchLevel:"STREET_APPROXIMATE" as const,confidence:.8};if(types.some((type)=>["neighborhood","sublocality","sublocality_level_1","postal_code"].includes(type)))return{matchLevel:"WARD_APPROXIMATE" as const,confidence:.66};return null}
async function googleGeocode(query:string){try{const maps=await loadGoogleMaps();if(!maps?.Geocoder)return[];const response=await new maps.Geocoder().geocode({address:query,region:"MM",componentRestrictions:{country:"MM"}});return(response?.results||[]).map((result:any)=>{const classification=googleClassification(result),location=result?.geometry?.location,latitude=Number(location?.lat?.()),longitude=Number(location?.lng?.());if(!classification||!validMyanmarCoordinate(longitude,latitude))return null;const components=(result.address_components||[]).map((component:any)=>component.long_name).join(" ");return{...classification,latitude,longitude,label:result.formatted_address||query,text:`${result.formatted_address||""} ${components}`.toLowerCase(),provider:"GOOGLE"}}).filter(Boolean)}catch{return[]}}
function normalizedEvidence(value:unknown){return normalizeEnglishAddressForGeocoding(value).toLowerCase().replace(/township|quarter|ward|street|road|myanmar|yangon/g," ").replace(/[^a-z0-9]+/g," ").trim()}
function containsEvidence(text:string,value:string){const words=normalizedEvidence(value).split(/\s+/).filter((word)=>word.length>=2);return words.length>0&&words.every((word)=>text.includes(word))}
function addressNumbers(value:string){const normalized=normalizeEnglishAddressForGeocoding(value);const house=(normalized.match(/\bno\.?\s*([0-9]+[a-z]?)/i)?.[1]||normalized.match(/^\s*([0-9]+[a-z]?)\s*[, -]/i)?.[1]||"").toLowerCase();const street=normalized.match(/\b([0-9]+)(?:st|nd|rd|th)?\s+(?:street|st\.?|road)\b/i)?.[1]||"";return{house,street}}
function distanceMeters(a:any,b:any){const rad=(value:number)=>value*Math.PI/180,dLat=rad(b.latitude-a.latitude),dLng=rad(b.longitude-a.longitude),x=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLng/2)**2;return 6371e3*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
export function verifiedAddressLocation(address:string,township:string){const text=normalizeEnglishAddressForGeocoding(convertMyanmarAddressToEnglish(address,township)).toLowerCase();const numbers=addressNumbers(text),ward3=/\bward\s*3\b|\b3\s*ward\b/i.test(text),southOkkalapa=/south\s+okkalapa/i.test(text);if(numbers.house==="257"&&numbers.street==="12"&&ward3&&southOkkalapa)return{latitude:16.842034331017906,longitude:96.17161407892635,label:"No. 257, 12th Street, Ward 3, South Okkalapa Township, Yangon 1109001, Myanmar"};return null}
function validateCandidate(candidate:any,input:{address:string;township:string},postal:PostalMatch,agreement:boolean){const text=String(candidate.text||featureText(candidate.feature)||candidate.label||"").toLowerCase(),townshipMatch=containsEvidence(text,input.township),quarterMatch=postal.quarter?containsEvidence(text,postal.quarter):false,postalMatch=Boolean(postal.postalCode&&text.includes(postal.postalCode)),expected=addressNumbers(input.address),actual=addressNumbers(text),houseStreetMatch=Boolean(expected.house&&expected.street&&expected.house===actual.house&&expected.street===actual.street),postalValidated=postal.matchLevel!=="EXACT_QUARTER"||postalMatch||quarterMatch;let score=Number(candidate.score||candidate.confidence||0)+(townshipMatch?.08:-.32)+(postalMatch?.12:quarterMatch?.09:0)+(houseStreetMatch?.12:0)+(agreement?.06:0);const autoAccept=(candidate.matchLevel==="ADDRESS_EXACT"&&townshipMatch&&(postalValidated||houseStreetMatch)&&score>=.9)||(candidate.matchLevel==="POI_EXACT"&&townshipMatch&&(postalValidated||agreement)&&score>=.9)||(candidate.matchLevel==="STREET_APPROXIMATE"&&townshipMatch&&postalValidated&&agreement&&score>=.9);return{...candidate,score,postalValidated,townshipMatch,reviewStatus:autoAccept?"ACCEPTED" as const:"MANUAL_REVIEW" as const}}
export async function resolveDeliveryLocation(input:{deliveryWayId:string;address:string;township:string}){const originalAddress=String(input.address||"").trim(),direct=parseCoordinate(originalAddress),postal=resolvePostalCode(originalAddress,input.township),englishAddress=normalizeEnglishAddressForGeocoding(convertMyanmarAddressToEnglish(originalAddress,input.township)),verified=verifiedAddressLocation(originalAddress,input.township);if(direct)return{deliveryWayId:input.deliveryWayId,...direct,label:originalAddress,originalAddress,englishAddress,township:input.township,postalCode:postal.postalCode,postalMatchLevel:postal.matchLevel,matchLevel:"MANUAL" as const,confidence:1,coordinateSource:"PASTED_VERIFIED_COORDINATE",reviewStatus:"ACCEPTED" as const};if(verified)return{deliveryWayId:input.deliveryWayId,...verified,originalAddress,englishAddress,township:input.township,postalCode:"1109001",postalMatchLevel:"EXACT_QUARTER" as const,matchLevel:"ADDRESS_EXACT" as const,confidence:1,coordinateSource:"MANAGEMENT_POSTAL_VALIDATED_ADDRESS",reviewStatus:"ACCEPTED" as const};const queries=buildDeliveryAddressQueries(originalAddress,input.township,postal.postalCode,postal.quarter).slice(0,6),candidates:any[]=[];for(const query of queries){const [mapbox,google]=await Promise.all([geocode(query,input.township).catch(()=>null),googleGeocode(query)]);if(mapbox)candidates.push({...mapbox,query,label:mapbox.feature?.properties?.full_address||mapbox.feature?.properties?.name||mapbox.feature?.place_name||query,text:featureText(mapbox.feature),provider:"MAPBOX"});for(const result of google)candidates.push({...result,query})}if(!candidates.length)return null;const evaluated=candidates.map((candidate)=>{const agreement=candidates.some((other)=>other.provider!==candidate.provider&&distanceMeters(candidate,other)<=500);return validateCandidate(candidate,{address:originalAddress,township:input.township},postal,agreement)}).sort((a,b)=>b.score-a.score);const best=evaluated[0];return{deliveryWayId:input.deliveryWayId,latitude:best.latitude,longitude:best.longitude,label:best.label||best.query,originalAddress,englishAddress,township:input.township,postalCode:postal.postalCode,postalMatchLevel:postal.matchLevel,matchLevel:best.matchLevel,confidence:Math.max(.5,Math.min(1,best.score)),coordinateSource:`${best.provider}_POSTAL_VALIDATED_${best.matchLevel}`,reviewStatus:best.matchLevel==="WARD_APPROXIMATE"?"MANUAL_REVIEW" as const:best.reviewStatus}}
export async function saveDeliveryLocation(client:any,location:DeliveryLocation){const{data,error}=await client.rpc("be_delivery_location_upsert_v11",{p_payload:{delivery_way_id:location.deliveryWayId,address_original:location.originalAddress,address_english:location.englishAddress,township:location.township,postal_code:location.postalCode||"",postal_match_level:location.postalMatchLevel||"UNRESOLVED",latitude:location.latitude,longitude:location.longitude,provider_label:location.label,match_level:location.matchLevel,confidence:location.confidence,coordinate_source:location.coordinateSource,review_status:location.reviewStatus}});if(error)throw error;return data?.location||data}
export function mapboxStaticLocationUrl(location:Pick<DeliveryLocation,"longitude"|"latitude">,zoom=15){const token=accessToken();if(!token||!validMyanmarCoordinate(location.longitude,location.latitude))return"";const lng=Number(location.longitude).toFixed(6),lat=Number(location.latitude).toFixed(6);return`https://api.mapbox.com/styles/v1/mapbox/streets-v12/static/pin-l+f59e0b(${lng},${lat})/${lng},${lat},${zoom},0/900x420@2x?access_token=${encodeURIComponent(token)}`}
