import { useEffect, useMemo, useState, type ReactNode } from "react";
import {
  AlertTriangle,
  Banknote,
  Building2,
  Calculator,
  CheckCircle2,
  Download,
  RefreshCw,
  Search,
  ShieldCheck,
} from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { calculateNaypyitawBranchSettlement, INTEGRATED_MASTER_BUILD } from "@/lib/integratedMasterSpec";

type Row = Record<string, any>;
type Snapshot = { build?:string; generated_at?:string; summary?:Record<string,any>; eligible_parcels?:Row[]; batches?:Row[]; remittances?:Row[]; adjustments?:Row[]; payments?:Row[]; disputes?:Row[]; audit?:Row[] };
const tabs=["Overview","Eligible Parcels","COD Remittance","Prepaid Revenue","Settlement Batches","Penalties & Adjustments","Payments","Disputes","Audit Log","Rule Configuration"];
const money=(v:unknown)=>`${Number(v||0).toLocaleString("en-US")} MMK`;
const text=(v:unknown,f="-")=>String(v??"").trim()||f;

export default function BranchOfficeSettlementPage(){
  const [tab,setTab]=useState("Overview");
  const [snapshot,setSnapshot]=useState<Snapshot>({});
  const [search,setSearch]=useState("");
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState("");
  const [preview,setPreview]=useState({revenue:6000,sender:"HQ" as "HQ"|"NPT",lastMile:"NPT" as "HQ"|"NPT",penalties:0,credits:0,deductions:0});

  async function load(){setLoading(true);setError("");try{const {data,error:rpcError}=await (supabase as any).rpc("be_branch_settlement_snapshot_v1",{p_branch_code:"NPT",p_payload:{tab}});if(rpcError)throw rpcError;const p=data?.data||data||{};setSnapshot({...p,eligible_parcels:Array.isArray(p.eligible_parcels)?p.eligible_parcels:[],batches:Array.isArray(p.batches)?p.batches:[],remittances:Array.isArray(p.remittances)?p.remittances:[],adjustments:Array.isArray(p.adjustments)?p.adjustments:[],payments:Array.isArray(p.payments)?p.payments:[],disputes:Array.isArray(p.disputes)?p.disputes:[],audit:Array.isArray(p.audit)?p.audit:[]});}catch(cause:any){setSnapshot({});setError(cause?.message||"Naypyitaw settlement backend is unavailable.");}finally{setLoading(false)}}
  useEffect(()=>{void load()},[tab]);

  const calculation=useMemo(()=>{try{return calculateNaypyitawBranchSettlement({shareableDeliveryRevenueMmk:preview.revenue,senderEntity:preview.sender,lastMileEntity:preview.lastMile,penaltiesMmk:preview.penalties,creditsMmk:preview.credits,deductionsMmk:preview.deductions})}catch{return null}},[preview]);
  const source=tab==="Eligible Parcels"?snapshot.eligible_parcels||[]:tab==="COD Remittance"?snapshot.remittances||[]:tab==="Settlement Batches"?snapshot.batches||[]:tab==="Penalties & Adjustments"?snapshot.adjustments||[]:tab==="Payments"?snapshot.payments||[]:tab==="Disputes"?snapshot.disputes||[]:tab==="Audit Log"?snapshot.audit||[]:[];
  const rows=source.filter((r)=>!search||JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));
  const s=snapshot.summary||{};

  function exportCsv(){const keys=Array.from(new Set(rows.flatMap((r)=>Object.keys(r))));const csv=[keys,...rows.map((r)=>keys.map((k)=>r[k]))].map((line)=>line.map((v)=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`npt-branch-settlement-${tab.toLowerCase().replaceAll(" ","-")}.csv`;a.click();URL.revokeObjectURL(url)}

  return <div className="space-y-6 text-[#eef8ff]" data-build={INTEGRATED_MASTER_BUILD}>
    <header className="flex flex-wrap items-start justify-between gap-4 border-b border-[#1a3a5c] pb-5"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.22em] text-[#f6b84b]"><Building2 size={15}/>NPT Phase 1</div><h1 className="mt-2 text-3xl font-black">Branch ↔ Head Office Settlement</h1><p className="mt-2 max-w-4xl text-[13px] leading-6 text-[#8fb4d0]">Naypyitaw-only 55% sender / 45% last-mile revenue share, 10% management fee on Naypyitaw's allocated gross share, COD custody, prepaid revenue, penalties and audited batch settlement.</p></div><div className="flex gap-2"><button onClick={exportCsv} disabled={!rows.length} className="action secondary"><Download size={15}/>Export</button><button onClick={()=>void load()} disabled={loading} className="action primary"><RefreshCw size={15} className={loading?"animate-spin":""}/>Refresh</button></div></header>

    <div className="flex items-start gap-3 rounded-2xl border border-amber-700/60 bg-amber-950/20 p-4 text-[12px] leading-6 text-amber-100"><AlertTriangle size={17} className="mt-1 shrink-0"/><div><strong>Active contract: NPT_INTEROFFICE_55_45_MGMT10_V1.</strong> Mandalay, DK Delivery and Royal Express do not inherit this rule. COD remittance and branch revenue sharing remain separate ledgers.</div></div>
    {error?<div className="rounded-2xl border border-rose-700 bg-rose-950/25 p-4 text-[12px] text-rose-200">{error} No demonstration rows are displayed.</div>:null}

    <section className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8"><Kpi label="Eligible Ways" value={text(s.eligible_ways,"0")}/><Kpi label="Shareable Revenue" value={money(s.shareable_revenue_mmk)}/><Kpi label="NPT Gross Share" value={money(s.npt_gross_share_mmk)}/><Kpi label="Management Fee" value={money(s.management_fee_mmk)}/><Kpi label="Penalties" value={money(s.penalties_mmk)}/><Kpi label="NPT Net Share" value={money(s.npt_net_share_mmk)}/><Kpi label="COD Outstanding" value={money(s.cod_outstanding_mmk)}/><Kpi label="Open Exceptions" value={text(s.exception_count,"0")}/></section>

    <div className="rounded-2xl border border-[#1a3a5c] bg-[#0b2236] p-2"><div className="flex gap-1 overflow-x-auto">{tabs.map((item)=><button key={item} onClick={()=>setTab(item)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-[11px] font-black ${tab===item?"bg-[#f6b84b] text-[#061524]":"text-[#8fb4d0] hover:bg-[#112b45]"}`}>{item}</button>)}</div></div>

    {tab==="Overview"?<Overview preview={preview} setPreview={setPreview} calculation={calculation}/>:tab==="Prepaid Revenue"?<PrepaidNote/>:tab==="Rule Configuration"?<RuleConfiguration/>:<section className="rounded-3xl border border-[#1a3a5c] bg-[#0b2236]"><div className="flex items-center gap-3 border-b border-[#1a3a5c] p-4"><div className="relative flex-1"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#6f98b8]"/><input value={search} onChange={(e)=>setSearch(e.target.value)} className="w-full rounded-xl border border-[#1a3a5c] bg-[#061524] py-2.5 pl-9 pr-3 text-[12px] outline-none focus:border-[#f6b84b]" placeholder="Search current settlement records..."/></div><span className="text-[11px] text-[#6f98b8]">{rows.length} rows</span></div><GenericTable rows={rows} loading={loading}/></section>}

    <div className="flex items-center gap-2 text-[10px] text-[#567d9b]"><ShieldCheck size={13}/>Backend: be_branch_settlement_snapshot_v1 · Build: {snapshot.build||"not returned"} · Generated: {snapshot.generated_at||"-"}</div>
    <style>{`.action{display:inline-flex;align-items:center;gap:8px;border-radius:12px;padding:10px 15px;font-size:12px;font-weight:900}.action.primary{background:#f6b84b;color:#061524}.action.secondary{border:1px solid #355a78;background:#081b2e;color:#d8ecfa}.action:disabled{opacity:.4}`}</style>
  </div>
}

function Kpi({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-[#1a3a5c] bg-[#0b2236] p-4"><div className="text-[9px] font-black uppercase tracking-wider text-[#6f98b8]">{label}</div><div className="mt-2 text-lg font-black">{value}</div></div>}
function Overview({preview,setPreview,calculation}:{preview:any;setPreview:(v:any)=>void;calculation:any}){return <div className="grid gap-5 lg:grid-cols-[1fr_1.2fr]"><section className="rounded-3xl border border-[#1a3a5c] bg-[#0b2236] p-5"><div className="mb-4 flex items-center gap-2 font-black uppercase tracking-wider text-[#f6b84b]"><Calculator size={15}/>Rule Calculator Preview</div><div className="grid grid-cols-2 gap-3"><Field label="Shareable Revenue"><input className={inp} type="number" min={0} value={preview.revenue} onChange={(e)=>setPreview({...preview,revenue:Number(e.target.value||0)})}/></Field><Field label="Sender"><select className={inp} value={preview.sender} onChange={(e)=>{const sender=e.target.value as "HQ"|"NPT";setPreview({...preview,sender,lastMile:sender==="HQ"?"NPT":"HQ"})}}><option>HQ</option><option>NPT</option></select></Field><Field label="Last Mile"><input className={`${inp} opacity-70`} readOnly value={preview.lastMile}/></Field><Field label="Penalties"><input className={inp} type="number" min={0} value={preview.penalties} onChange={(e)=>setPreview({...preview,penalties:Number(e.target.value||0)})}/></Field><Field label="Other Deductions"><input className={inp} type="number" min={0} value={preview.deductions} onChange={(e)=>setPreview({...preview,deductions:Number(e.target.value||0)})}/></Field><Field label="Approved Credits"><input className={inp} type="number" min={0} value={preview.credits} onChange={(e)=>setPreview({...preview,credits:Number(e.target.value||0)})}/></Field></div><div className="mt-4 text-[10px] leading-5 text-[#6f98b8]">This browser calculator is explanatory only. Batch amounts are recalculated and snapshotted by the backend.</div></section><section className="rounded-3xl border border-[#1a3a5c] bg-[#0b2236] p-5"><div className="mb-4 flex items-center gap-2 font-black uppercase tracking-wider text-[#f6b84b]"><Banknote size={15}/>Calculated Allocation</div>{calculation?<div className="grid grid-cols-2 gap-3 md:grid-cols-3"><Kpi label="Sender Gross 55%" value={money(calculation.senderGrossMmk)}/><Kpi label="Last-Mile Gross 45%" value={money(calculation.lastMileGrossMmk)}/><Kpi label="NPT Gross" value={money(calculation.nptGrossMmk)}/><Kpi label="NPT Management Fee 10%" value={money(calculation.nptManagementFeeMmk)}/><Kpi label="NPT Net" value={money(calculation.nptNetMmk)}/><Kpi label="HQ Total Revenue" value={money(calculation.hqTotalRevenueMmk)}/></div>:<div className="text-rose-300">Invalid sender/last-mile combination.</div>}<div className="mt-5 rounded-xl border border-[#1a3a5c] bg-[#061524] p-4 text-[11px] leading-6 text-[#8fb4d0]"><strong className="text-[#eef8ff]">COD rule:</strong> Naypyitaw remits gross customer/COD custody to Head Office. Head Office pays the approved NPT net share separately. Merchant settlement is not changed by this internal allocation.</div></section></div>}
const inp="w-full rounded-xl border border-[#1a3a5c] bg-[#061524] px-3 py-2.5 text-[12px] outline-none focus:border-[#f6b84b]";
function Field({label,children}:{label:string;children:ReactNode}){return <label className="space-y-1.5 text-[10px] font-black uppercase tracking-wider text-[#6f98b8]">{label}{children}</label>}
function PrepaidNote(){return <section className="rounded-3xl border border-[#1a3a5c] bg-[#0b2236] p-6"><div className="flex items-center gap-2 text-[#f6b84b]"><CheckCircle2 size={16}/><strong>Prepaid settlement eligibility</strong></div><p className="mt-3 max-w-4xl text-[12px] leading-6 text-[#8fb4d0]">A prepaid parcel enters the 55/45 share only after delivered status, recognized Britium payment, verified sender and last-mile roles, approved POD, valid lineage and no financial hold. Customer collection at delivery remains zero.</p></section>}
function RuleConfiguration(){return <section className="rounded-3xl border border-[#1a3a5c] bg-[#0b2236] p-6"><div className="font-black uppercase tracking-wider text-[#f6b84b]">NPT_INTEROFFICE_55_45_MGMT10_V1</div><div className="mt-4 grid gap-3 md:grid-cols-2"><Kpi label="Sender Share" value="55%"/><Kpi label="Last-Mile Share" value="45%"/><Kpi label="NPT Management Fee" value="10% of NPT allocated gross share"/><Kpi label="Settlement Method" value="Gross COD remittance + separate branch payment"/></div><div className="mt-4 text-[11px] leading-6 text-[#8fb4d0]">Configuration changes require Head Office Finance authority, effective dates, maker-checker approval and an immutable rule version. Mandalay and external providers use separate contracts.</div></section>}
function GenericTable({rows,loading}:{rows:Row[];loading:boolean}){const keys=rows.length?Array.from(new Set(rows.flatMap((r)=>Object.keys(r)))).slice(0,14):[];return <div className="overflow-auto"><table className="w-full min-w-[1000px] text-left text-[11px]"><thead className="bg-[#081b2e] uppercase tracking-wider text-[#6f98b8]"><tr>{keys.map((k)=><th key={k} className="p-3">{k.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={Math.max(keys.length,1)} className="p-10 text-center text-[#6f98b8]">Loading...</td></tr>:rows.length?rows.map((r,i)=><tr key={i} className="border-t border-[#1a3a5c]">{keys.map((k)=><td key={k} className="max-w-[260px] p-3">{typeof r[k]==="number"&&/amount|fee|share|cod|revenue|payable|credit|deduction|penalty/i.test(k)?money(r[k]):text(r[k])}</td>)}</tr>):<tr><td className="p-10 text-center text-[#6f98b8]">No backend records for this tab.</td></tr>}</tbody></table></div>}
