const GOOGLE_MATRIX_URL = "https://routes.googleapis.com/distanceMatrix/v2:computeRouteMatrix";
const MAPBOX_MATRIX_BASE = "https://api.mapbox.com/directions-matrix/v1/mapbox/driving";
const GOOGLE_BATCH = 10;
const MAPBOX_BATCH = 12;

function env(...names){for(const name of names){const value=String(process.env[name]||"").trim();if(value)return value;}return "";}
function json(body,status=200,headers={}){return Response.json(body,{status,headers:{"Cache-Control":"no-store",...headers}});}
function point(value){const latitude=Number(value?.latitude),longitude=Number(value?.longitude);if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>90||Math.abs(longitude)>180)throw new Error("Every route point requires valid latitude and longitude.");return{latitude,longitude};}
function normalizeStops(stops){if(!Array.isArray(stops)||!stops.length)throw new Error("At least one delivery stop is required.");if(stops.length>75)throw new Error("A delivery van is limited to 75 route stops.");const seen=new Set();return stops.map((stop,index)=>{const id=String(stop?.delivery_way_id||stop?.id||"").trim();if(!id)throw new Error(`Stop ${index+1} has no delivery_way_id.`);if(seen.has(id))throw new Error(`Duplicate delivery stop: ${id}`);seen.add(id);return{...stop,delivery_way_id:id,...point(stop)};});}
function seconds(value){const parsed=Number(String(value||"0s").replace(/s$/,"").trim());return Number.isFinite(parsed)?parsed:0;}
function pathCost(order,durations,distances){let duration=0,distance=0;for(let i=1;i<order.length;i+=1){const from=order[i-1],to=order[i],d=Number(durations[from]?.[to]),m=Number(distances[from]?.[to]);if(!Number.isFinite(d)||!Number.isFinite(m))return{duration:Number.POSITIVE_INFINITY,distance:Number.POSITIVE_INFINITY};duration+=d;distance+=m;}return{duration,distance};}
function optimizeMatrix(durations,distances){const count=durations.length,remaining=new Set(Array.from({length:count-1},(_,i)=>i+1)),order=[0];while(remaining.size){const current=order[order.length-1];let best=null;for(const candidate of remaining){const duration=Number(durations[current]?.[candidate]),distance=Number(distances[current]?.[candidate]);if(!Number.isFinite(duration)||!Number.isFinite(distance))continue;if(!best||duration<best.duration||(duration===best.duration&&distance<best.distance)||(duration===best.duration&&distance===best.distance&&candidate<best.index))best={index:candidate,duration,distance};}if(!best)throw new Error("Road matrix contains an unreachable remaining stop.");order.push(best.index);remaining.delete(best.index);}let bestOrder=order,bestCost=pathCost(bestOrder,durations,distances);for(let pass=0;pass<3;pass+=1){let improved=false;for(let i=1;i<bestOrder.length-1;i+=1){for(let k=i+1;k<bestOrder.length;k+=1){const candidate=bestOrder.slice(0,i).concat(bestOrder.slice(i,k+1).reverse(),bestOrder.slice(k+1)),cost=pathCost(candidate,durations,distances);if(cost.duration+0.001<bestCost.duration||(Math.abs(cost.duration-bestCost.duration)<0.001&&cost.distance<bestCost.distance)){bestOrder=candidate;bestCost=cost;improved=true;}}}if(!improved)break;}return{order:bestOrder,...bestCost};}
function parseGoogleMatrix(text){try{const parsed=JSON.parse(text);return Array.isArray(parsed)?parsed:[parsed];}catch{return text.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map(line=>JSON.parse(line));}}
function googleWaypoint(p){return{waypoint:{location:{latLng:{latitude:p.latitude,longitude:p.longitude}}}};}
async function googleMatrix(points,apiKey){const n=points.length,durations=Array.from({length:n},()=>Array(n).fill(Number.POSITIVE_INFINITY)),distances=Array.from({length:n},()=>Array(n).fill(Number.POSITIVE_INFINITY));for(let i=0;i<n;i+=1){durations[i][i]=0;distances[i][i]=0;}let requestCount=0;for(let oi=0;oi<n;oi+=GOOGLE_BATCH){const origins=points.slice(oi,oi+GOOGLE_BATCH);for(let di=0;di<n;di+=GOOGLE_BATCH){const destinations=points.slice(di,di+GOOGLE_BATCH);requestCount+=1;const response=await fetch(GOOGLE_MATRIX_URL,{method:"POST",headers:{"Content-Type":"application/json","X-Goog-Api-Key":apiKey,"X-Goog-FieldMask":"originIndex,destinationIndex,status,condition,distanceMeters,duration"},body:JSON.stringify({origins:origins.map(googleWaypoint),destinations:destinations.map(googleWaypoint),travelMode:"DRIVE",routingPreference:"TRAFFIC_AWARE",units:"METRIC"})});const body=await response.text();if(!response.ok)throw new Error(`Google Routes matrix failed (${response.status}): ${body.slice(0,220)}`);for(const element of parseGoogleMatrix(body)){const originIndex=oi+Number(element.originIndex),destinationIndex=di+Number(element.destinationIndex);if(!Number.isInteger(originIndex)||!Number.isInteger(destinationIndex))continue;const statusCode=Number(element?.status?.code||0);if(statusCode!==0||String(element?.condition||"ROUTE_EXISTS")==="ROUTE_NOT_FOUND")continue;const duration=seconds(element.duration),distance=Number(element.distanceMeters);if(Number.isFinite(duration)&&Number.isFinite(distance)){durations[originIndex][destinationIndex]=duration;distances[originIndex][destinationIndex]=distance;}}}}return{durations,distances,requestCount};}
async function mapboxMatrix(points,token){const n=points.length,durations=Array.from({length:n},()=>Array(n).fill(Number.POSITIVE_INFINITY)),distances=Array.from({length:n},()=>Array(n).fill(Number.POSITIVE_INFINITY));for(let i=0;i<n;i+=1){durations[i][i]=0;distances[i][i]=0;}let requestCount=0;for(let oi=0;oi<n;oi+=MAPBOX_BATCH){const origins=points.slice(oi,oi+MAPBOX_BATCH);for(let di=0;di<n;di+=MAPBOX_BATCH){const destinations=points.slice(di,di+MAPBOX_BATCH),combined=[...origins,...destinations],sourceIndexes=origins.map((_,i)=>i).join(";"),destinationIndexes=destinations.map((_,i)=>origins.length+i).join(";"),coordinates=combined.map(p=>`${p.longitude},${p.latitude}`).join(";");requestCount+=1;const response=await fetch(`${MAPBOX_MATRIX_BASE}/${coordinates}?sources=${sourceIndexes}&destinations=${destinationIndexes}&annotations=duration,distance&access_token=${encodeURIComponent(token)}`);const body=await response.json().catch(()=>({}));if(!response.ok||body?.code!=="Ok")throw new Error(`Mapbox road matrix failed (${response.status}): ${String(body?.message||body?.code||"unknown error")}`);for(let i=0;i<origins.length;i+=1)for(let j=0;j<destinations.length;j+=1){const duration=Number(body?.durations?.[i]?.[j]),distance=Number(body?.distances?.[i]?.[j]);if(Number.isFinite(duration)&&Number.isFinite(distance)){durations[oi+i][di+j]=duration;distances[oi+i][di+j]=distance;}}}}return{durations,distances,requestCount};}
async function verifySupabaseUser(request){const authorization=String(request.headers.get("authorization")||"");if(!/^Bearer\s+\S+/i.test(authorization))return false;const url=env("SUPABASE_URL","VITE_SUPABASE_URL").replace(/\/+$/,"");const key=env("SUPABASE_ANON_KEY","VITE_SUPABASE_ANON_KEY");if(!url||!key)return false;try{const response=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:authorization}});return response.ok;}catch{return false;}}
async function googleHealthProbe(apiKey){const points=[{latitude:16.8409,longitude:96.1735},{latitude:16.8512,longitude:96.1811}];const matrix=await googleMatrix(points,apiKey),result=optimizeMatrix(matrix.durations,matrix.distances);return Number.isFinite(result.distance)&&result.distance>0;}

export default{async fetch(request){try{const url=new URL(request.url),googleKey=env("GOOGLE_ROUTES_API_KEY","GOOGLE_MAPS_API_KEY","VITE_GOOGLE_MAPS_API_KEY"),mapboxToken=env("MAPBOX_ACCESS_TOKEN","VITE_MAPBOX_ACCESS_TOKEN","VITE_MAPBOX_TOKEN");if(request.method==="GET"&&url.searchParams.get("health")==="1"){const probe=url.searchParams.get("probe")==="1";let googleRoutesVerified=false,probeError="";if(probe&&googleKey){try{googleRoutesVerified=await googleHealthProbe(googleKey);}catch(error){probeError=String(error?.message||error).slice(0,240);}}return json({ok:Boolean(googleKey||mapboxToken),google_routes_configured:Boolean(googleKey),google_routes_verified:probe?googleRoutesVerified:null,mapbox_fallback_configured:Boolean(mapboxToken),road_routing_available:Boolean((probe&&googleRoutesVerified)||mapboxToken),probe_error:probeError||null},(googleKey||mapboxToken)?200:503,{"Cache-Control":probe?"public, s-maxage=300, stale-while-revalidate=60":"no-store"});}
if(request.method!=="POST")return json({ok:false,error:"method_not_allowed"},405,{Allow:"POST, GET"});if(!(await verifySupabaseUser(request)))return json({ok:false,error:"authenticated_wayplan_session_required"},401);const payload=await request.json().catch(()=>({})),origin=point(payload?.origin),stops=normalizeStops(payload?.stops),points=[origin,...stops],diagnostics=[];
if(googleKey){try{const matrix=await googleMatrix(points,googleKey),optimized=optimizeMatrix(matrix.durations,matrix.distances);return json({ok:true,source:"GOOGLE_ROUTES",route_mode:points.length>GOOGLE_BATCH?"GOOGLE_ROUTE_MATRIX_BATCHED_LOCAL_2OPT":"GOOGLE_ROUTE_MATRIX_LOCAL_2OPT",ordered_stops:optimized.order.slice(1).map((index,sequence)=>({...stops[index-1],sequence:sequence+1})),distance_m:Math.round(optimized.distance),duration_s:Math.round(optimized.duration),request_count:matrix.requestCount,fallback:false,optimized_at:new Date().toISOString()});}catch(error){diagnostics.push(`Google Routes: ${String(error?.message||error).slice(0,300)}`);}}else diagnostics.push("Google Routes: API key is not configured in the Vercel runtime.");
if(mapboxToken){try{const matrix=await mapboxMatrix(points,mapboxToken),optimized=optimizeMatrix(matrix.durations,matrix.distances);return json({ok:true,source:"MAPBOX_FALLBACK",route_mode:"MAPBOX_BATCHED_ROAD_MATRIX_LOCAL_2OPT",ordered_stops:optimized.order.slice(1).map((index,sequence)=>({...stops[index-1],sequence:sequence+1})),distance_m:Math.round(optimized.distance),duration_s:Math.round(optimized.duration),request_count:matrix.requestCount,fallback:true,warning:"Google Routes was unavailable; Mapbox road-time/distance matrix was used. This is still road-based routing, not straight-line geographic routing.",diagnostics,optimized_at:new Date().toISOString()});}catch(error){diagnostics.push(`Mapbox: ${String(error?.message||error).slice(0,300)}`);}}
return json({ok:false,error:"road_routing_unavailable",message:"Automatic Wayplan generation requires a real road-routing matrix. Straight-line geographic fallback is disabled.",diagnostics},503);
}catch(error){return json({ok:false,error:String(error?.message||error)},400);}}};
