-- Full Operational Wayplan: Rider allocation, immutable generated/road route versions,
-- immutable warehouse LIFO snapshot, audited stop events and Rider rerouting.

create table if not exists public.be_wayplan_route_versions (
  wayplan_id text not null,
  route_version integer not null,
  route_kind text not null check (route_kind in ('GENERATED','RIDER_REROUTE')),
  optimizer_source text not null,
  route_mode text not null,
  origin jsonb not null default '{}'::jsonb,
  ordered_stops jsonb not null,
  distance_m bigint not null default 0,
  duration_s bigint not null default 0,
  request_count integer not null default 0,
  generated_by text,
  generated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  primary key (wayplan_id, route_version)
);

create table if not exists public.be_wayplan_active_routes (
  wayplan_id text primary key,
  current_route_version integer not null,
  updated_at timestamptz not null default now(),
  updated_by text
);

create table if not exists public.be_wayplan_warehouse_route_snapshots (
  wayplan_id text primary key,
  generated_route_version integer not null,
  delivery_order jsonb not null,
  lifo_load_order jsonb not null,
  locked_at timestamptz not null default now(),
  locked_by text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.be_wayplan_stop_events (
  id bigint generated by default as identity primary key,
  wayplan_id text not null,
  delivery_way_id text not null,
  route_version integer,
  event_type text not null check (event_type in ('ARRIVED','DELIVERED','CUSTOMER_UNAVAILABLE','RESCHEDULE','RTO','SKIP')),
  actor_code text,
  actor_role text,
  actor_user_id uuid,
  event_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);
create index if not exists idx_be_wayplan_stop_events_wayplan_time on public.be_wayplan_stop_events(wayplan_id,event_at,id);
create index if not exists idx_be_wayplan_stop_events_delivery on public.be_wayplan_stop_events(delivery_way_id,event_at,id);

create or replace function public.be_wayplan_immutable_row_guard()
returns trigger language plpgsql set search_path=public,pg_temp as $$
begin
  raise exception using errcode='55000', message='Generated Wayplan route and warehouse loading history is immutable.';
end $$;

revoke all on function public.be_wayplan_immutable_row_guard() from public,anon,authenticated;

drop trigger if exists trg_be_wayplan_route_versions_immutable on public.be_wayplan_route_versions;
create trigger trg_be_wayplan_route_versions_immutable before update or delete on public.be_wayplan_route_versions
for each row execute function public.be_wayplan_immutable_row_guard();

drop trigger if exists trg_be_wayplan_warehouse_snapshot_immutable on public.be_wayplan_warehouse_route_snapshots;
create trigger trg_be_wayplan_warehouse_snapshot_immutable before update or delete on public.be_wayplan_warehouse_route_snapshots
for each row execute function public.be_wayplan_immutable_row_guard();

alter table public.be_wayplan_route_versions enable row level security;
alter table public.be_wayplan_active_routes enable row level security;
alter table public.be_wayplan_warehouse_route_snapshots enable row level security;
alter table public.be_wayplan_stop_events enable row level security;

create or replace function public.be_multi_van_context()
returns jsonb language plpgsql stable security definer set search_path=public,auth,pg_temp as $$
declare
  v_options jsonb; v_vehicles jsonb; v_busy jsonb; v_role text; v_origins jsonb;
begin
  v_role:=lower(public.be_current_user_role());
  if auth.uid() is null or v_role not in ('superadmin','super_admin','admin','dispatch','wayplan_operator','supervisor') then
    raise exception using errcode='42501',message='Wayplan operator permission is required.';
  end if;
  v_options:=public.be_wayplan_assignment_options_v44();
  select coalesce(jsonb_agg(jsonb_build_object('id',record_key,'name',payload->>'vehicle_no','capacity_kg',payload->'capacity_kg','operation_type',payload->>'operation_type') order by record_key),'[]'::jsonb)
  into v_vehicles from public.be_master_data_rows
  where dataset_key='fleet_master' and deleted_at is null and upper(coalesce(status,'ACTIVE'))='ACTIVE'
    and upper(coalesce(payload->>'status','ACTIVE')) in ('ACTIVE','ASSIGNED') and payload->>'operation_type' in ('DELIVERY','PICKUP_HIGHWAY');
  select coalesce(jsonb_agg(jsonb_build_object('vehicle_code',vehicle_code,'driver_code',driver_code,'rider_code',rider_code,'helper_code',helper_code)),'[]'::jsonb)
  into v_busy from public.be_wayplan_dispatches where upper(coalesce(wayplan_status,'CREATED')) not in ('CANCELLED','COMPLETED','CLOSED');
  select coalesce(jsonb_object_agg(case branch_code when 'YGN' then 'YANGON' when 'MDY' then 'MANDALAY' when 'NPT' then 'NAYPYITAW' end,
    jsonb_build_object('branch_code',branch_code,'label',branch_name,'latitude',lat,'longitude',lng)),'{}'::jsonb)
  into v_origins from public.be_branch_offices
  where branch_code in ('YGN','MDY','NPT') and coalesce(active,true)=true and lat is not null and lng is not null;
  return jsonb_build_object('vehicles',v_vehicles,'drivers',v_options->'drivers','riders',v_options->'riders','helpers',v_options->'helpers','busy',v_busy,'route_origins',v_origins);
end $$;
revoke all on function public.be_multi_van_context() from public,anon;
grant execute on function public.be_multi_van_context() to authenticated;

create or replace function public.be_wayplan_append_route_version(
  p_wayplan_id text,p_route_kind text,p_optimizer_source text,p_route_mode text,p_ordered_stops jsonb,
  p_distance_m bigint default 0,p_duration_s bigint default 0,p_request_count integer default 0,
  p_actor text default null,p_metadata jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
  v_kind text:=upper(btrim(coalesce(p_route_kind,''))); v_source text:=upper(btrim(coalesce(p_optimizer_source,'')));
  v_mode text:=upper(btrim(coalesce(p_route_mode,''))); v_version int; v_count int; v_expected int;
  v_ids text[]; v_origin jsonb:='{}'::jsonb; v_lifo jsonb; v_actor text:=coalesce(nullif(p_actor,''),auth.jwt()->>'email',auth.uid()::text);
begin
  if v_kind not in ('GENERATED','RIDER_REROUTE') then raise exception 'Invalid route kind.'; end if;
  if v_source not in ('GOOGLE_ROUTES','MAPBOX_FALLBACK','GEOGRAPHIC_FALLBACK') then raise exception 'Invalid optimizer source.'; end if;
  if jsonb_typeof(p_ordered_stops)<>'array' or jsonb_array_length(p_ordered_stops)=0 then raise exception 'Ordered route stops are required.'; end if;
  perform 1 from public.be_wayplan_dispatches where wayplan_id=p_wayplan_id for update;
  if not found then raise exception 'Wayplan not found.'; end if;
  select count(*) into v_count from jsonb_array_elements(p_ordered_stops);
  select array_agg(id order by id) into v_ids from (select value->>'delivery_way_id' id from jsonb_array_elements(p_ordered_stops)) q;
  if exists(select 1 from (select value->>'delivery_way_id' id,count(*) c from jsonb_array_elements(p_ordered_stops) group by 1 having count(*)>1) d) then raise exception 'Route contains duplicate parcel IDs.'; end if;
  if exists(select 1 from jsonb_array_elements(p_ordered_stops) x where not exists(select 1 from public.be_wayplan_dispatch_stops s where s.wayplan_id=p_wayplan_id and s.delivery_way_id=x.value->>'delivery_way_id')) then raise exception 'Route contains a parcel outside this Wayplan.'; end if;
  select count(*) into v_expected from public.be_wayplan_dispatch_stops where wayplan_id=p_wayplan_id;
  if v_kind='GENERATED' and v_count<>v_expected then raise exception 'Generated route must contain every Wayplan stop exactly once.'; end if;
  select coalesce(max(route_version),0)+1 into v_version from public.be_wayplan_route_versions where wayplan_id=p_wayplan_id;
  select coalesce((select value from jsonb_each((public.be_multi_van_context()->'route_origins')) where value->>'branch_code'=(select branch_code from public.be_wayplan_dispatches where wayplan_id=p_wayplan_id) limit 1),'{}'::jsonb) into v_origin;
  insert into public.be_wayplan_route_versions(wayplan_id,route_version,route_kind,optimizer_source,route_mode,origin,ordered_stops,distance_m,duration_s,request_count,generated_by,metadata)
  values(p_wayplan_id,v_version,v_kind,v_source,v_mode,v_origin,p_ordered_stops,greatest(coalesce(p_distance_m,0),0),greatest(coalesce(p_duration_s,0),0),greatest(coalesce(p_request_count,0),0),v_actor,coalesce(p_metadata,'{}'::jsonb));
  insert into public.be_wayplan_active_routes(wayplan_id,current_route_version,updated_by) values(p_wayplan_id,v_version,v_actor)
  on conflict(wayplan_id) do update set current_route_version=excluded.current_route_version,updated_at=now(),updated_by=excluded.updated_by;
  update public.be_wayplan_dispatches set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('current_route_version',v_version,'current_route_source',v_source,'current_route_mode',v_mode),updated_at=now() where wayplan_id=p_wayplan_id;
  if v_kind='GENERATED' then
    select coalesce(jsonb_agg(value order by ord desc),'[]'::jsonb) into v_lifo from jsonb_array_elements(p_ordered_stops) with ordinality x(value,ord);
    insert into public.be_wayplan_warehouse_route_snapshots(wayplan_id,generated_route_version,delivery_order,lifo_load_order,locked_by,metadata)
    values(p_wayplan_id,v_version,p_ordered_stops,v_lifo,v_actor,jsonb_build_object('optimizer_source',v_source,'route_mode',v_mode,'immutable',true))
    on conflict(wayplan_id) do nothing;
    update public.be_wayplan_dispatches set warehouse_metadata=coalesce(warehouse_metadata,'{}'::jsonb)||jsonb_build_object('generated_route_version',v_version,'warehouse_route_locked',true,'warehouse_load_strategy','LIFO') where wayplan_id=p_wayplan_id;
  end if;
  return jsonb_build_object('ok',true,'wayplan_id',p_wayplan_id,'route_version',v_version,'route_kind',v_kind,'optimizer_source',v_source,'route_mode',v_mode);
end $$;
revoke all on function public.be_wayplan_append_route_version(text,text,text,text,jsonb,bigint,bigint,integer,text,jsonb) from public,anon;
grant execute on function public.be_wayplan_append_route_version(text,text,text,text,jsonb,bigint,bigint,integer,text,jsonb) to authenticated;

create or replace function public.be_generate_multi_van(p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
 ctx jsonb; plans jsonb:=p_payload->'plans'; p jsonb; v jsonb; driver jsonb; rider jsonb; helper jsonb;
 request_id text:=p_payload->>'request_id'; region text:=upper(p_payload->>'region_code'); old_event jsonb; result jsonb; route_result jsonb;
 results jsonb:='[]'; ids text[]:='{}'; crews text[]:='{}'; vans text[]:='{}'; parcel_id text; n int; short_count int:=0; total_count int:=0; weight numeric;
 reason text:=btrim(coalesce(p_payload->>'below_minimum_reason','')); actor text; plan_id text; idx int:=0; branch text;
 route jsonb; ordered jsonb;
begin
 ctx:=public.be_multi_van_context(); actor:=coalesce(auth.jwt()->>'email',auth.uid()::text);
 if request_id is null or request_id !~ '^[a-fA-F0-9-]{36}$' then raise exception 'A stable request ID is required.'; end if;
 if plans is null or jsonb_typeof(plans)<>'array' or jsonb_array_length(plans) not between 1 and 7 then raise exception 'Select one to seven delivery vans.'; end if;
 if region not in ('YANGON','MANDALAY','NAYPYITAW') then raise exception 'Choose an active delivery region.'; end if;
 branch:=case region when 'YANGON' then 'YGN' when 'MANDALAY' then 'MDY' else 'NPT' end;
 perform pg_advisory_xact_lock(hashtextextended('britium-multi-van-planner',0));
 select details into old_event from public.be_audit_events where action='MULTI_VAN_CREATED' and resource_id=request_id limit 1;
 if old_event is not null then if old_event->'request' is distinct from p_payload or old_event->>'actor_id'<>auth.uid()::text then raise exception 'Request ID already belongs to another operation.'; end if; return old_event->'result'; end if;
 for p in select value from jsonb_array_elements(plans) loop
   n:=jsonb_array_length(p->'delivery_way_ids'); if n is null or n<1 then raise exception 'Each activated van needs parcels.'; end if;
   total_count:=total_count+n; if n<50 then short_count:=short_count+1; end if; if n>75 then raise exception 'A delivery van cannot exceed 75 parcels.'; end if;
   select x into v from jsonb_array_elements(ctx->'vehicles') x where x->>'id'=p->>'vehicle_code' and x->>'operation_type'='DELIVERY'; if v is null then raise exception 'Choose a delivery van; pickup/highway vehicles are reserved.'; end if;
   if (p->>'vehicle_code')=any(vans) then raise exception 'A van cannot be allocated twice.'; end if; vans:=array_append(vans,p->>'vehicle_code');
   select x into driver from jsonb_array_elements(ctx->'drivers') x where x->>'id'=p->>'driver_code'; if driver is null then raise exception 'Choose an active, authenticated driver.'; end if;
   select x into rider from jsonb_array_elements(ctx->'riders') x where x->>'id'=p->>'rider_code'; if rider is null then raise exception 'Choose an active, authenticated rider.'; end if;
   helper:=null; if coalesce(p->>'helper_code','')<>'' then select x into helper from jsonb_array_elements(ctx->'helpers') x where x->>'id'=p->>'helper_code'; if helper is null then raise exception 'Choose an active helper or leave helper empty.'; end if; end if;
   if coalesce(driver->>'branch_code','') not in ('',branch) or coalesce(rider->>'branch_code','') not in ('',branch) or (helper is not null and coalesce(helper->>'branch_code','') not in ('',branch)) then raise exception 'Selected crew belongs to another branch.'; end if;
   if p->>'driver_code'=p->>'rider_code' or (helper is not null and (p->>'helper_code'=p->>'driver_code' or p->>'helper_code'=p->>'rider_code')) then raise exception 'Driver, Rider and Helper must be different people.'; end if;
   if (p->>'driver_code')=any(crews) or (p->>'rider_code')=any(crews) or (helper is not null and (p->>'helper_code')=any(crews)) then raise exception 'A crew member cannot serve two crew positions or two vans in this plan.'; end if;
   crews:=array_append(crews,p->>'driver_code'); crews:=array_append(crews,p->>'rider_code'); if helper is not null then crews:=array_append(crews,p->>'helper_code'); end if;
   if exists(select 1 from jsonb_array_elements(ctx->'busy') b where b->>'vehicle_code'=p->>'vehicle_code'
      or p->>'driver_code' in (b->>'driver_code',b->>'rider_code',b->>'helper_code') or p->>'rider_code' in (b->>'driver_code',b->>'rider_code',b->>'helper_code')
      or (helper is not null and p->>'helper_code' in (b->>'driver_code',b->>'rider_code',b->>'helper_code'))) then raise exception 'A selected vehicle or crew member already has an active Wayplan. Refresh availability.'; end if;
   for parcel_id in select jsonb_array_elements_text(p->'delivery_way_ids') loop if parcel_id=any(ids) then raise exception 'A parcel cannot belong to two vans.'; end if; ids:=array_append(ids,parcel_id); end loop;
   select coalesce(sum(weight_kg),0) into weight from public.be_data_entry_parcel_details where delivery_way_id in (select jsonb_array_elements_text(p->'delivery_way_ids'));
   if coalesce((v->>'capacity_kg')::numeric,0)>0 and weight>(v->>'capacity_kg')::numeric then raise exception 'Selected parcel weight exceeds vehicle capacity.'; end if;
 end loop;
 if short_count>1 then raise exception 'Only one delivery van may be below 50 parcels.'; end if;
 if short_count=1 and (coalesce((p_payload->>'approve_below_minimum')::boolean,false) is not true or length(reason)<5) then raise exception 'Operator approval and a reason are required for the van below 50 parcels.'; end if;
 perform 1 from public.be_data_entry_parcel_details where delivery_way_id=any(ids) order by delivery_way_id for update;
 for p in select value from jsonb_array_elements(plans) loop
   idx:=idx+1; plan_id:='WP-'||to_char(now(),'YYYYMMDD')||'-'||request_id||'-'||idx;
   if exists(select 1 from public.be_wayplan_dispatches where wayplan_id=plan_id) then raise exception 'Wayplan identifier already exists.'; end if;
   select x into v from jsonb_array_elements(ctx->'vehicles') x where x->>'id'=p->>'vehicle_code'; select x into driver from jsonb_array_elements(ctx->'drivers') x where x->>'id'=p->>'driver_code'; select x into rider from jsonb_array_elements(ctx->'riders') x where x->>'id'=p->>'rider_code'; select x into helper from jsonb_array_elements(ctx->'helpers') x where x->>'id'=p->>'helper_code';
   result:=public.be_generate_wayplan(p||jsonb_build_object('wayplan_id',plan_id,'region_code',region,'vehicle_name',v->>'name','driver_name',driver->>'name','rider_name',rider->>'name','helper_name',coalesce(helper->>'name',''),'actor',actor));
   if not coalesce((result->>'ok')::boolean,false) then raise exception '%',coalesce(result->>'error','Wayplan creation failed.'); end if;
   update public.be_wayplan_dispatches set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('multi_van_request',request_id,'operator_id',auth.uid(),'below_minimum',jsonb_array_length(p->'delivery_way_ids')<50,'below_minimum_reason',reason) where wayplan_id=plan_id;
   update public.be_wayplan_dispatch_stops set stop_sequence=stop_sequence+100000 where wayplan_id=plan_id;
   update public.be_wayplan_dispatch_stops s set stop_sequence=x.ord::int from jsonb_array_elements_text(p->'delivery_way_ids') with ordinality x(id,ord) where s.wayplan_id=plan_id and s.delivery_way_id=x.id;
   select jsonb_agg(jsonb_build_object('delivery_way_id',x.id,'sequence',x.ord,'waybill_no',s.waybill_no,'recipient_name',s.recipient_name,'recipient_phone',s.recipient_phone,'address',s.address,'township',s.township) order by x.ord)
   into ordered from jsonb_array_elements_text(p->'delivery_way_ids') with ordinality x(id,ord) join public.be_wayplan_dispatch_stops s on s.wayplan_id=plan_id and s.delivery_way_id=x.id;
   route:=coalesce(p->'route','{}'::jsonb);
   route_result:=public.be_wayplan_append_route_version(plan_id,'GENERATED',coalesce(route->>'source','GEOGRAPHIC_FALLBACK'),coalesce(route->>'route_mode','GEOGRAPHIC_NEAREST_NEIGHBOUR_EMERGENCY'),ordered,coalesce((route->>'distance_m')::bigint,0),coalesce((route->>'duration_s')::bigint,0),coalesce((route->>'request_count')::int,0),actor,route);
   result:=result||jsonb_build_object('wayplan_id',plan_id,'generated_route',route_result); results:=results||jsonb_build_array(result);
   if jsonb_array_length(p->'delivery_way_ids')<50 then insert into public.be_audit_events(actor_id,actor_email,actor_role,action,resource_type,resource_id,details) values(auth.uid(),actor,public.be_current_user_role(),'MULTI_VAN_BELOW_MINIMUM_APPROVED','WAYPLAN',plan_id,jsonb_build_object('vehicle',v,'parcel_count',jsonb_array_length(p->'delivery_way_ids'),'reason',reason,'request_id',request_id)); end if;
 end loop;
 result:=jsonb_build_object('ok',true,'wayplans',results,'parcel_count',total_count);
 insert into public.be_audit_events(actor_id,actor_email,actor_role,action,resource_type,resource_id,details) values(auth.uid(),actor,public.be_current_user_role(),'MULTI_VAN_CREATED','WAYPLAN_BATCH',request_id,jsonb_build_object('request',p_payload,'result',result,'actor_id',auth.uid()));
 return result;
end $$;
revoke all on function public.be_generate_multi_van(jsonb) from public,anon;
grant execute on function public.be_generate_multi_van(jsonb) to authenticated;

create or replace function public.be_rider_operational_route_snapshot(p_wayplan_id text default null)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
  ident jsonb:=private.be_field_primary_context_v101(); code text:=upper(coalesce(ident->>'worker_code','')); role text:=lower(coalesce(ident->>'role',''));
  wp text:=nullif(btrim(coalesce(p_wayplan_id,'')),''); ver int; route public.be_wayplan_route_versions%rowtype; warehouse jsonb; stops jsonb; current jsonb;
begin
  if auth.uid() is null or role not in ('rider','driver','helper') then raise exception 'Authenticated field session is required.'; end if;
  if wp is null then select wayplan_id into wp from public.be_wayplan_dispatches where upper(coalesce(wayplan_status,'CREATED')) not in ('CANCELLED','COMPLETED','CLOSED') and case role when 'driver' then upper(coalesce(driver_code,''))=code when 'helper' then upper(coalesce(helper_code,''))=code else upper(coalesce(rider_code,''))=code end order by planned_at desc nulls last,created_at desc nulls last limit 1; end if;
  if wp is null then return jsonb_build_object('ok',true,'wayplan_id',null,'stops','[]'::jsonb,'message','No active Wayplan assigned.'); end if;
  if not exists(select 1 from public.be_wayplan_dispatches where wayplan_id=wp and case role when 'driver' then upper(coalesce(driver_code,''))=code when 'helper' then upper(coalesce(helper_code,''))=code else upper(coalesce(rider_code,''))=code end) then raise exception 'Wayplan is not assigned to the signed-in worker.'; end if;
  select current_route_version into ver from public.be_wayplan_active_routes where wayplan_id=wp; if ver is null then select max(route_version) into ver from public.be_wayplan_route_versions where wayplan_id=wp; end if;
  select * into route from public.be_wayplan_route_versions where wayplan_id=wp and route_version=ver;
  select to_jsonb(w) into warehouse from public.be_wayplan_warehouse_route_snapshots w where wayplan_id=wp;
  select coalesce(jsonb_agg(jsonb_build_object('sequence',(x.value->>'sequence')::int,'delivery_way_id',x.value->>'delivery_way_id','waybill_no',coalesce(s.waybill_no,x.value->>'waybill_no'),'recipient_name',coalesce(s.recipient_name,x.value->>'recipient_name'),'recipient_phone',coalesce(s.recipient_phone,x.value->>'recipient_phone'),'address',coalesce(s.address,x.value->>'address'),'township',coalesce(s.township,x.value->>'township'),'notes',coalesce(s.metadata->>'delivery_notes',s.metadata->>'notes',''),'status',coalesce(s.stop_status,s.rider_status,'PENDING'),'latitude',coalesce(nullif(s.metadata->>'latitude','')::numeric,nullif(s.metadata->>'lat','')::numeric),'longitude',coalesce(nullif(s.metadata->>'longitude','')::numeric,nullif(s.metadata->>'lng','')::numeric)) order by (x.value->>'sequence')::int),'[]'::jsonb)
  into stops from jsonb_array_elements(route.ordered_stops) x left join public.be_wayplan_dispatch_stops s on s.wayplan_id=wp and s.delivery_way_id=x.value->>'delivery_way_id';
  select value into current from jsonb_array_elements(stops) value where upper(coalesce(value->>'status','PENDING')) not in ('DELIVERED','RTO','SKIP','RESCHEDULE','CUSTOMER_UNAVAILABLE','RETURN_TO_WAREHOUSE','FAILED_DELIVERY') order by (value->>'sequence')::int limit 1;
  return jsonb_build_object('ok',true,'wayplan_id',wp,'route_version',ver,'route_kind',route.route_kind,'optimizer_source',route.optimizer_source,'route_mode',route.route_mode,'distance_m',route.distance_m,'duration_s',route.duration_s,'current_stop',current,'stops',stops,'warehouse_snapshot',warehouse,'warehouse_route_immutable',warehouse is not null);
end $$;
revoke all on function public.be_rider_operational_route_snapshot(text) from public,anon;
grant execute on function public.be_rider_operational_route_snapshot(text) to authenticated;

create or replace function public.be_rider_operational_route_action(p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
 ident jsonb:=private.be_field_primary_context_v101(); code text:=upper(coalesce(ident->>'worker_code','')); role text:=lower(coalesce(ident->>'role','')); uid uuid:=auth.uid();
 wp text:=nullif(btrim(p_payload->>'wayplan_id'),''); did text:=nullif(btrim(p_payload->>'delivery_way_id'),''); action text:=upper(btrim(coalesce(p_payload->>'action',''))); ver int; base jsonb;
begin
 if uid is null or role not in ('rider','driver') then return jsonb_build_object('ok',false,'error','PRIMARY_RIDER_OR_DRIVER_REQUIRED'); end if;
 if wp is null or did is null then return jsonb_build_object('ok',false,'error','wayplan_id and delivery_way_id are required'); end if;
 if not exists(select 1 from public.be_wayplan_dispatches where wayplan_id=wp and (upper(coalesce(rider_code,''))=code or upper(coalesce(driver_code,''))=code)) then return jsonb_build_object('ok',false,'error','WAYPLAN_NOT_ASSIGNED_TO_SIGNED_IN_WORKER'); end if;
 select current_route_version into ver from public.be_wayplan_active_routes where wayplan_id=wp;
 if action='ARRIVED' then
   base:=public.be_rider_wayplan_action(p_payload||jsonb_build_object('action','arrived'));
   if not coalesce((base->>'ok')::boolean,false) then return base; end if;
 elsif action in ('CUSTOMER_UNAVAILABLE','RESCHEDULE','RTO','SKIP') then
   update public.be_wayplan_dispatch_stops set rider_status=action,stop_status=action,rider_action_at=now(),failed_reason=case when action='CUSTOMER_UNAVAILABLE' then coalesce(nullif(p_payload->>'remark',''),'Customer unavailable') else failed_reason end,metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('last_rider_route_action',action,'last_rider_route_action_at',now(),'last_rider_route_remark',p_payload->>'remark'),updated_at=now() where wayplan_id=wp and delivery_way_id=did;
   if not found then return jsonb_build_object('ok',false,'error','Wayplan stop not found'); end if;
 else return jsonb_build_object('ok',false,'error','Invalid route action','allowed_actions',jsonb_build_array('ARRIVED','CUSTOMER_UNAVAILABLE','RESCHEDULE','RTO','SKIP')); end if;
 insert into public.be_wayplan_stop_events(wayplan_id,delivery_way_id,route_version,event_type,actor_code,actor_role,actor_user_id,payload) values(wp,did,ver,action,code,role,uid,coalesce(p_payload,'{}'::jsonb));
 return public.be_rider_operational_route_snapshot(wp)||jsonb_build_object('action',action,'reroute_required',action in ('CUSTOMER_UNAVAILABLE','RESCHEDULE','RTO','SKIP'));
end $$;
revoke all on function public.be_rider_operational_route_action(jsonb) from public,anon;
grant execute on function public.be_rider_operational_route_action(jsonb) to authenticated;

create or replace function public.be_rider_apply_operational_reroute(p_wayplan_id text,p_route jsonb)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
 ident jsonb:=private.be_field_primary_context_v101(); code text:=upper(coalesce(ident->>'worker_code','')); role text:=lower(coalesce(ident->>'role','')); actor text:=coalesce(auth.jwt()->>'email',code); result jsonb;
begin
 if auth.uid() is null or role not in ('rider','driver') then raise exception 'Primary Rider or Driver is required.'; end if;
 if not exists(select 1 from public.be_wayplan_dispatches where wayplan_id=p_wayplan_id and (upper(coalesce(rider_code,''))=code or upper(coalesce(driver_code,''))=code)) then raise exception 'Wayplan is not assigned to the signed-in worker.'; end if;
 result:=public.be_wayplan_append_route_version(p_wayplan_id,'RIDER_REROUTE',coalesce(p_route->>'source','GEOGRAPHIC_FALLBACK'),coalesce(p_route->>'route_mode','GEOGRAPHIC_NEAREST_NEIGHBOUR_EMERGENCY'),coalesce(p_route->'ordered_stops','[]'::jsonb),coalesce((p_route->>'distance_m')::bigint,0),coalesce((p_route->>'duration_s')::bigint,0),coalesce((p_route->>'request_count')::int,0),actor,p_route);
 return public.be_rider_operational_route_snapshot(p_wayplan_id)||jsonb_build_object('reroute',result,'warehouse_route_regenerated',false);
end $$;
revoke all on function public.be_rider_apply_operational_reroute(text,jsonb) from public,anon;
grant execute on function public.be_rider_apply_operational_reroute(text,jsonb) to authenticated;

create or replace function public.be_wayplan_delivery_event_audit()
returns trigger language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare ver int;
begin
 if upper(coalesce(new.stop_status,new.rider_status,''))='DELIVERED' and upper(coalesce(old.stop_status,old.rider_status,''))<>'DELIVERED' then
   select current_route_version into ver from public.be_wayplan_active_routes where wayplan_id=new.wayplan_id;
   insert into public.be_wayplan_stop_events(wayplan_id,delivery_way_id,route_version,event_type,actor_code,actor_role,actor_user_id,payload)
   values(new.wayplan_id,new.delivery_way_id,ver,'DELIVERED',coalesce(new.rider_code,new.metadata->>'confirmed_by_workforce_code'),coalesce(new.metadata->>'authenticated_worker_role','rider'),auth.uid(),jsonb_build_object('delivered_at',coalesce(new.delivered_at,now()),'proof_url',coalesce(new.rider_proof_url,new.proof_url)));
 end if;
 return new;
end $$;
revoke all on function public.be_wayplan_delivery_event_audit() from public,anon,authenticated;
drop trigger if exists trg_be_wayplan_delivery_event_audit on public.be_wayplan_dispatch_stops;
create trigger trg_be_wayplan_delivery_event_audit after update of stop_status,rider_status,delivered_at on public.be_wayplan_dispatch_stops for each row execute function public.be_wayplan_delivery_event_audit();
