-- Full Operational Wayplan: immutable route versions, warehouse route snapshots,
-- Rider crew allocation and auditable stop events.
-- Additive migration. Existing Wayplans and historical warehouse data are not rewritten.

create table if not exists public.be_wayplan_route_versions_v1 (
  wayplan_id text not null,
  route_version integer not null check (route_version > 0),
  route_scope text not null check (route_scope in ('GENERATED','RIDER_REROUTE')),
  route_source text not null check (route_source in ('GOOGLE_ROUTES','MAPBOX_FALLBACK','GEOGRAPHIC_FALLBACK')),
  route_mode text not null,
  ordered_stops jsonb not null check (jsonb_typeof(ordered_stops)='array'),
  distance_m bigint not null default 0,
  duration_s bigint not null default 0,
  request_count integer not null default 0,
  parent_route_version integer,
  generated_by text,
  generated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  primary key (wayplan_id, route_version)
);

create index if not exists idx_be_wayplan_route_versions_v1_latest
  on public.be_wayplan_route_versions_v1(wayplan_id, route_version desc);

create table if not exists public.be_wayplan_warehouse_load_snapshot_v1 (
  wayplan_id text primary key,
  generated_route_version integer not null,
  delivery_order jsonb not null check (jsonb_typeof(delivery_order)='array'),
  load_order jsonb not null check (jsonb_typeof(load_order)='array'),
  created_by text,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.be_wayplan_stop_events_v1 (
  id bigint generated by default as identity primary key,
  wayplan_id text not null,
  delivery_way_id text not null,
  event_type text not null check (event_type in ('ARRIVED','DELIVERED','CUSTOMER_UNAVAILABLE','RESCHEDULE','RTO','SKIP')),
  route_version integer,
  original_stop_sequence integer,
  active_stop_sequence integer,
  actor_code text,
  actor_role text,
  event_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);

create index if not exists idx_be_wayplan_stop_events_v1_wayplan
  on public.be_wayplan_stop_events_v1(wayplan_id,event_at,id);

alter table public.be_wayplan_route_versions_v1 enable row level security;
alter table public.be_wayplan_warehouse_load_snapshot_v1 enable row level security;
alter table public.be_wayplan_stop_events_v1 enable row level security;

drop policy if exists be_wayplan_route_versions_v1_read on public.be_wayplan_route_versions_v1;
create policy be_wayplan_route_versions_v1_read on public.be_wayplan_route_versions_v1
for select to authenticated using (true);

drop policy if exists be_wayplan_warehouse_load_snapshot_v1_read on public.be_wayplan_warehouse_load_snapshot_v1;
create policy be_wayplan_warehouse_load_snapshot_v1_read on public.be_wayplan_warehouse_load_snapshot_v1
for select to authenticated using (true);

drop policy if exists be_wayplan_stop_events_v1_read on public.be_wayplan_stop_events_v1;
create policy be_wayplan_stop_events_v1_read on public.be_wayplan_stop_events_v1
for select to authenticated using (true);

create or replace function public.be_wayplan_immutable_row_guard_v1()
returns trigger language plpgsql set search_path=public,pg_temp as $$
begin
  raise exception using errcode='55000', message='Generated Wayplan route history is immutable.';
end $$;

revoke all on function public.be_wayplan_immutable_row_guard_v1() from public,anon,authenticated;

drop trigger if exists trg_be_wayplan_route_versions_v1_immutable on public.be_wayplan_route_versions_v1;
create trigger trg_be_wayplan_route_versions_v1_immutable
before update or delete on public.be_wayplan_route_versions_v1
for each row execute function public.be_wayplan_immutable_row_guard_v1();

drop trigger if exists trg_be_wayplan_warehouse_snapshot_v1_immutable on public.be_wayplan_warehouse_load_snapshot_v1;
create trigger trg_be_wayplan_warehouse_snapshot_v1_immutable
before update or delete on public.be_wayplan_warehouse_load_snapshot_v1
for each row execute function public.be_wayplan_immutable_row_guard_v1();

-- Driver / Rider / Helper must be mutually exclusive on each allocation.
create or replace function public.be_wayplan_distinct_crew_guard_v1()
returns trigger language plpgsql set search_path=public,pg_temp as $$
declare d text:=upper(btrim(coalesce(new.driver_code,'')));
declare r text:=upper(btrim(coalesce(new.rider_code,'')));
declare h text:=upper(btrim(coalesce(new.helper_code,'')));
begin
  if d<>'' and r<>'' and d=r then raise exception using errcode='23514',message='Driver and Rider must be different people.'; end if;
  if d<>'' and h<>'' and d=h then raise exception using errcode='23514',message='Driver and Helper must be different people.'; end if;
  if r<>'' and h<>'' and r=h then raise exception using errcode='23514',message='Rider and Helper must be different people.'; end if;
  return new;
end $$;

revoke all on function public.be_wayplan_distinct_crew_guard_v1() from public,anon,authenticated;
drop trigger if exists trg_be_wayplan_distinct_crew_v1 on public.be_wayplan_dispatches;
create trigger trg_be_wayplan_distinct_crew_v1
before insert or update of driver_code,rider_code,helper_code on public.be_wayplan_dispatches
for each row execute function public.be_wayplan_distinct_crew_guard_v1();

-- Keep existing assignment source, but expose Rider and all three active branch origins.
create or replace function public.be_multi_van_context()
returns jsonb language plpgsql stable security definer set search_path=public,auth,pg_temp as $$
declare
  v_options jsonb; v_vehicles jsonb; v_busy jsonb; v_role text; v_origins jsonb:='{}'::jsonb;
begin
  v_role:=lower(public.be_current_user_role());
  if auth.uid() is null or v_role not in ('superadmin','super_admin','admin','dispatch','wayplan_operator','supervisor') then
    raise exception using errcode='42501',message='Wayplan operator permission is required.';
  end if;
  v_options:=public.be_wayplan_assignment_options_v44();
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',record_key,'name',payload->>'vehicle_no','capacity_kg',payload->'capacity_kg','operation_type',payload->>'operation_type'
  ) order by record_key),'[]'::jsonb) into v_vehicles
  from public.be_master_data_rows
  where dataset_key='fleet_master' and deleted_at is null
    and upper(coalesce(status,'ACTIVE'))='ACTIVE'
    and upper(coalesce(payload->>'status','ACTIVE')) in ('ACTIVE','ASSIGNED')
    and payload->>'operation_type' in ('DELIVERY','PICKUP_HIGHWAY');

  select coalesce(jsonb_agg(jsonb_build_object(
    'vehicle_code',vehicle_code,'driver_code',driver_code,'rider_code',rider_code,'helper_code',helper_code
  )),'[]'::jsonb) into v_busy
  from public.be_wayplan_dispatches
  where upper(coalesce(wayplan_status,'CREATED')) not in ('CANCELLED','COMPLETED','CLOSED');

  select coalesce(jsonb_object_agg(region_code,origin),'{}'::jsonb) into v_origins
  from (
    select case branch_code when 'YGN' then 'YANGON' when 'MDY' then 'MANDALAY' when 'NPT' then 'NAYPYITAW' end region_code,
      jsonb_build_object('branch_code',branch_code,'label',branch_name,'latitude',lat,'longitude',lng) origin
    from public.be_branch_offices
    where branch_code in ('YGN','MDY','NPT') and coalesce(active,true)=true and lat is not null and lng is not null
  ) q where region_code is not null;

  return jsonb_build_object('vehicles',v_vehicles,'drivers',v_options->'drivers','riders',v_options->'riders','helpers',v_options->'helpers','busy',v_busy,'route_origins',v_origins);
end $$;
revoke all on function public.be_multi_van_context() from public,anon;
grant execute on function public.be_multi_van_context() to authenticated;

-- Append an immutable active road route version. Warehouse snapshot is never touched here.
create or replace function public.be_wayplan_append_route_version_v1(p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
  v_wayplan text:=nullif(btrim(p_payload->>'wayplan_id'),'');
  v_scope text:=upper(coalesce(nullif(p_payload->>'route_scope',''),'RIDER_REROUTE'));
  v_source text:=upper(coalesce(nullif(p_payload->>'route_source',''),'GEOGRAPHIC_FALLBACK'));
  v_mode text:=coalesce(nullif(p_payload->>'route_mode',''),'GEOGRAPHIC_NEAREST_NEIGHBOUR_EMERGENCY');
  v_stops jsonb:=coalesce(p_payload->'ordered_stops','[]'::jsonb);
  v_actor text:=coalesce(public.be_field_team_code_from_login_v51(coalesce(auth.jwt()->>'email','')),auth.uid()::text);
  v_role text:=lower(public.be_current_user_role());
  v_current integer; v_next integer; v_ids text[]; v_expected text[]; v_item jsonb; v_seq integer:=0;
begin
  if auth.uid() is null then raise exception using errcode='42501',message='Authenticated Wayplan session required.'; end if;
  if v_wayplan is null then raise exception 'wayplan_id is required'; end if;
  if v_scope not in ('GENERATED','RIDER_REROUTE') then raise exception 'Invalid route scope'; end if;
  if v_source not in ('GOOGLE_ROUTES','MAPBOX_FALLBACK','GEOGRAPHIC_FALLBACK') then raise exception 'Invalid route source'; end if;
  if jsonb_typeof(v_stops)<>'array' or jsonb_array_length(v_stops)=0 then raise exception 'ordered_stops are required'; end if;

  perform 1 from public.be_wayplan_dispatches where wayplan_id=v_wayplan for update;
  if not found then raise exception 'Wayplan not found'; end if;

  if v_role in ('rider','driver','helper') and not exists(
    select 1 from public.be_wayplan_membership_v40 m where m.wayplan_id=v_wayplan and
      case v_role when 'driver' then upper(coalesce(m.driver_code,''))=upper(v_actor)
                  when 'helper' then upper(coalesce(m.helper_code,''))=upper(v_actor)
                  else upper(coalesce(m.rider_code,''))=upper(v_actor) end
  ) then raise exception using errcode='42501',message='Wayplan is not assigned to signed-in worker.'; end if;

  select array_agg(id order by id) into v_ids from (
    select btrim(value->>'delivery_way_id') id from jsonb_array_elements(v_stops) value
  ) s where id<>'';
  if cardinality(v_ids)<>jsonb_array_length(v_stops) or cardinality(v_ids)<>cardinality(array(select distinct unnest(v_ids))) then
    raise exception 'Every route stop requires one unique delivery_way_id';
  end if;

  if v_scope='RIDER_REROUTE' then
    select array_agg(delivery_way_id order by delivery_way_id) into v_expected
    from public.be_wayplan_dispatch_stops
    where wayplan_id=v_wayplan and upper(coalesce(stop_status,'')) not in ('DELIVERED','RETURN_TO_WAREHOUSE','RTO','SKIPPED','RESCHEDULED','CUSTOMER_UNAVAILABLE');
    if coalesce(v_ids,'{}'::text[]) is distinct from coalesce(v_expected,'{}'::text[]) then
      raise exception 'Rider reroute must contain every remaining eligible stop exactly once.';
    end if;
  end if;

  select max(route_version) into v_current from public.be_wayplan_route_versions_v1 where wayplan_id=v_wayplan;
  v_next:=coalesce(v_current,0)+1;
  insert into public.be_wayplan_route_versions_v1(
    wayplan_id,route_version,route_scope,route_source,route_mode,ordered_stops,distance_m,duration_s,request_count,parent_route_version,generated_by,metadata
  ) values (
    v_wayplan,v_next,v_scope,v_source,v_mode,v_stops,
    greatest(coalesce(nullif(p_payload->>'distance_m','')::bigint,0),0),
    greatest(coalesce(nullif(p_payload->>'duration_s','')::bigint,0),0),
    greatest(coalesce(nullif(p_payload->>'request_count','')::integer,0),0),
    v_current,v_actor,coalesce(p_payload->'metadata','{}'::jsonb)
  );

  -- Active road sequence may change; immutable warehouse snapshot does not.
  for v_item in select value from jsonb_array_elements(v_stops) loop
    v_seq:=v_seq+1;
    update public.be_wayplan_dispatch_stops
      set optimized_sequence=v_seq,
          route_code=v_wayplan||'-RV'||lpad(v_next::text,3,'0'),
          metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('active_route_version',v_next,'active_route_sequence',v_seq,'active_route_source',v_source),
          updated_at=now()
    where wayplan_id=v_wayplan and delivery_way_id=v_item->>'delivery_way_id';
  end loop;

  update public.be_wayplan_dispatches set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object(
    'generated_route_version',coalesce((metadata->>'generated_route_version')::integer,case when v_scope='GENERATED' then v_next else 1 end),
    'active_route_version',v_next,'active_route_source',v_source,'active_route_mode',v_mode
  ),updated_at=now() where wayplan_id=v_wayplan;

  return jsonb_build_object('ok',true,'wayplan_id',v_wayplan,'route_version',v_next,'route_scope',v_scope,'route_source',v_source);
end $$;
revoke all on function public.be_wayplan_append_route_version_v1(jsonb) from public,anon;
grant execute on function public.be_wayplan_append_route_version_v1(jsonb) to authenticated;

-- Route event snapshot for Rider Current Stop -> action -> Next Stop.
create or replace function public.be_wayplan_active_route_snapshot_v1(p_wayplan_id text)
returns jsonb language plpgsql stable security definer set search_path=public,auth,pg_temp as $$
declare v_version integer; v_source text; v_mode text; v_stops jsonb; v_current jsonb; v_warehouse integer; v_plan jsonb;
begin
  if auth.uid() is null then raise exception using errcode='42501',message='Authentication required.'; end if;
  select route_version,route_source,route_mode,ordered_stops into v_version,v_source,v_mode,v_stops
  from public.be_wayplan_route_versions_v1 where wayplan_id=p_wayplan_id order by route_version desc limit 1;
  if v_version is null then raise exception 'No generated route version exists for this Wayplan.'; end if;

  select generated_route_version into v_warehouse from public.be_wayplan_warehouse_load_snapshot_v1 where wayplan_id=p_wayplan_id;
  select to_jsonb(d) into v_plan from public.be_wayplan_dispatches d where d.wayplan_id=p_wayplan_id;

  select to_jsonb(q) into v_current from (
    select s.delivery_way_id,s.waybill_no,s.recipient_name,s.recipient_phone,s.address,s.township,s.stop_status,
      s.optimized_sequence as active_stop_sequence,
      s.metadata->>'notes' as notes,
      nullif(s.metadata#>>'{coordinates,latitude}','')::numeric as latitude,
      nullif(s.metadata#>>'{coordinates,longitude}','')::numeric as longitude
    from public.be_wayplan_dispatch_stops s
    where s.wayplan_id=p_wayplan_id and upper(coalesce(s.stop_status,'')) not in ('DELIVERED','RETURN_TO_WAREHOUSE','RTO','SKIPPED','RESCHEDULED','CUSTOMER_UNAVAILABLE')
    order by coalesce(s.optimized_sequence,s.stop_sequence),s.stop_sequence limit 1
  ) q;

  return jsonb_build_object('ok',true,'wayplan',v_plan,'route_version',v_version,'route_source',v_source,'route_mode',v_mode,
    'warehouse_generated_route_version',v_warehouse,'warehouse_route_immutable',true,'current_stop',v_current,
    'stops',(select coalesce(jsonb_agg(jsonb_build_object(
      'delivery_way_id',s.delivery_way_id,'waybill_no',s.waybill_no,'recipient_name',s.recipient_name,'recipient_phone',s.recipient_phone,
      'address',s.address,'township',s.township,'status',s.stop_status,'active_sequence',s.optimized_sequence,'original_sequence',s.stop_sequence,
      'notes',s.metadata->>'notes') order by coalesce(s.optimized_sequence,s.stop_sequence),s.stop_sequence),'[]'::jsonb)
      from public.be_wayplan_dispatch_stops s where s.wayplan_id=p_wayplan_id));
end $$;
revoke all on function public.be_wayplan_active_route_snapshot_v1(text) from public,anon;
grant execute on function public.be_wayplan_active_route_snapshot_v1(text) to authenticated;

-- Non-delivery-result route actions. DELIVERED continues through be_rider_wayplan_action so proof/payment/signature controls remain intact.
create or replace function public.be_wayplan_stop_event_action_v1(p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
  v_identity jsonb:=private.be_field_primary_context_v101(); v_code text:=upper(coalesce(v_identity->>'worker_code','')); v_role text:=lower(coalesce(v_identity->>'role',''));
  v_wayplan text:=nullif(btrim(p_payload->>'wayplan_id'),''); v_delivery text:=nullif(btrim(p_payload->>'delivery_way_id'),'');
  v_event text:=upper(coalesce(p_payload->>'event_type','')); v_status text; v_version integer; v_orig integer; v_active integer;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'error','AUTHENTICATED_FIELD_SESSION_REQUIRED'); end if;
  if v_role not in ('rider','driver') then return jsonb_build_object('ok',false,'error','PRIMARY_WORKER_REQUIRED'); end if;
  if v_event not in ('CUSTOMER_UNAVAILABLE','RESCHEDULE','RTO','SKIP') then return jsonb_build_object('ok',false,'error','INVALID_ROUTE_EVENT'); end if;
  if not exists(select 1 from public.be_wayplan_membership_v40 m where m.wayplan_id=v_wayplan and m.delivery_way_id=v_delivery and
    case v_role when 'driver' then upper(coalesce(m.driver_code,''))=v_code else upper(coalesce(m.rider_code,''))=v_code end)
  then return jsonb_build_object('ok',false,'error','WAYPLAN_NOT_ASSIGNED_TO_SIGNED_IN_WORKER'); end if;

  select stop_sequence,optimized_sequence into v_orig,v_active from public.be_wayplan_dispatch_stops where wayplan_id=v_wayplan and delivery_way_id=v_delivery for update;
  if not found then return jsonb_build_object('ok',false,'error','Wayplan stop not found'); end if;
  select max(route_version) into v_version from public.be_wayplan_route_versions_v1 where wayplan_id=v_wayplan;
  v_status:=case v_event when 'CUSTOMER_UNAVAILABLE' then 'CUSTOMER_UNAVAILABLE' when 'RESCHEDULE' then 'RESCHEDULED' when 'RTO' then 'RETURN_TO_WAREHOUSE' else 'SKIPPED' end;
  update public.be_wayplan_dispatch_stops set stop_status=v_status,rider_status=v_status,rider_action_at=now(),
    failed_reason=coalesce(nullif(p_payload->>'reason',''),failed_reason),updated_at=now(),
    metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('last_route_event',v_event,'last_route_event_at',now(),'last_route_event_by',v_code)
  where wayplan_id=v_wayplan and delivery_way_id=v_delivery;
  insert into public.be_wayplan_stop_events_v1(wayplan_id,delivery_way_id,event_type,route_version,original_stop_sequence,active_stop_sequence,actor_code,actor_role,payload)
  values(v_wayplan,v_delivery,v_event,v_version,v_orig,v_active,v_code,v_role,p_payload);
  return jsonb_build_object('ok',true,'wayplan_id',v_wayplan,'delivery_way_id',v_delivery,'event_type',v_event,'status',v_status,'reroute_remaining',true);
end $$;
revoke all on function public.be_wayplan_stop_event_action_v1(jsonb) from public,anon;
grant execute on function public.be_wayplan_stop_event_action_v1(jsonb) to authenticated;

-- Audit ARRIVED and DELIVERED generated through the existing proof-controlled action path.
create or replace function public.be_wayplan_audit_primary_stop_transition_v1()
returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare v_event text; v_version integer;
begin
  if coalesce(new.stop_status,'') is not distinct from coalesce(old.stop_status,'') then return new; end if;
  v_event:=case upper(coalesce(new.stop_status,'')) when 'ARRIVED_AT_CUSTOMER' then 'ARRIVED' when 'DELIVERED' then 'DELIVERED' else null end;
  if v_event is null then return new; end if;
  select max(route_version) into v_version from public.be_wayplan_route_versions_v1 where wayplan_id=new.wayplan_id;
  insert into public.be_wayplan_stop_events_v1(wayplan_id,delivery_way_id,event_type,route_version,original_stop_sequence,active_stop_sequence,actor_code,actor_role,payload)
  values(new.wayplan_id,new.delivery_way_id,v_event,v_version,new.stop_sequence,new.optimized_sequence,coalesce(new.rider_code,''),'rider',jsonb_build_object('stop_status',new.stop_status));
  return new;
end $$;
revoke all on function public.be_wayplan_audit_primary_stop_transition_v1() from public,anon,authenticated;
drop trigger if exists trg_be_wayplan_audit_primary_stop_transition_v1 on public.be_wayplan_dispatch_stops;
create trigger trg_be_wayplan_audit_primary_stop_transition_v1
after update of stop_status on public.be_wayplan_dispatch_stops
for each row execute function public.be_wayplan_audit_primary_stop_transition_v1();

-- Extend atomic multi-van generation. Existing 50-75, below-minimum approval and idempotency rules remain.
create or replace function public.be_generate_multi_van(p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
 ctx jsonb; plans jsonb:=p_payload->'plans'; p jsonb; v jsonb; driver jsonb; rider jsonb; helper jsonb;
 request_id text:=p_payload->>'request_id'; region text:=upper(p_payload->>'region_code'); branch text;
 old_event jsonb; result jsonb; results jsonb:='[]'; ids text[]:='{}'; crews text[]:='{}'; vans text[]:='{}';
 parcel_id text; n int; short_count int:=0; total_count int:=0; weight numeric;
 reason text:=btrim(coalesce(p_payload->>'below_minimum_reason','')); actor text; plan_id text; idx int:=0;
 route jsonb; route_ids text[]; plan_ids text[]; route_source text; route_mode text; delivery_json jsonb; load_json jsonb;
begin
 ctx:=public.be_multi_van_context(); actor:=coalesce(auth.jwt()->>'email',auth.uid()::text);
 if request_id is null or request_id !~ '^[a-fA-F0-9-]{36}$' then raise exception 'A stable request ID is required.'; end if;
 if plans is null or jsonb_typeof(plans)<>'array' or jsonb_array_length(plans) not between 1 and 7 then raise exception 'Select one to seven delivery vans.'; end if;
 if region not in ('YANGON','MANDALAY','NAYPYITAW') then raise exception 'Choose an active delivery region.'; end if;
 branch:=case region when 'YANGON' then 'YGN' when 'MANDALAY' then 'MDY' else 'NPT' end;
 perform pg_advisory_xact_lock(hashtextextended('britium-multi-van-planner',0));
 select details into old_event from public.be_audit_events where action='MULTI_VAN_CREATED' and resource_id=request_id limit 1;
 if old_event is not null then
   if old_event->'request' is distinct from p_payload or old_event->>'actor_id'<>auth.uid()::text then raise exception 'Request ID already belongs to another operation.'; end if;
   return old_event->'result';
 end if;

 for p in select value from jsonb_array_elements(plans) loop
   n:=jsonb_array_length(p->'delivery_way_ids'); if n is null or n<1 then raise exception 'Each activated van needs parcels.'; end if;
   if n>75 then raise exception 'A delivery van cannot exceed 75 parcels.'; end if;
   total_count:=total_count+n; if n<50 then short_count:=short_count+1; end if;
   select x into v from jsonb_array_elements(ctx->'vehicles') x where x->>'id'=p->>'vehicle_code' and x->>'operation_type'='DELIVERY';
   if v is null then raise exception 'Choose a delivery van; pickup/highway vehicles are reserved.'; end if;
   if (p->>'vehicle_code')=any(vans) then raise exception 'A van cannot be allocated twice.'; end if; vans:=array_append(vans,p->>'vehicle_code');
   select x into driver from jsonb_array_elements(ctx->'drivers') x where x->>'id'=p->>'driver_code';
   select x into rider from jsonb_array_elements(ctx->'riders') x where x->>'id'=p->>'rider_code';
   if driver is null then raise exception 'Choose an active, authenticated Driver.'; end if;
   if rider is null then raise exception 'Choose an active, authenticated Rider.'; end if;
   if coalesce(driver->>'branch_code','') not in ('',branch) then raise exception 'Driver belongs to another branch.'; end if;
   if coalesce(rider->>'branch_code','') not in ('',branch) then raise exception 'Rider belongs to another branch.'; end if;
   helper:=null; if coalesce(p->>'helper_code','')<>'' then select x into helper from jsonb_array_elements(ctx->'helpers') x where x->>'id'=p->>'helper_code'; if helper is null then raise exception 'Choose an active Helper or leave Helper empty.'; end if; end if;
   if helper is not null and coalesce(helper->>'branch_code','') not in ('',branch) then raise exception 'Helper belongs to another branch.'; end if;
   if upper(p->>'driver_code')=upper(p->>'rider_code') or (helper is not null and upper(p->>'helper_code') in (upper(p->>'driver_code'),upper(p->>'rider_code'))) then raise exception 'Driver, Rider and Helper must be different people.'; end if;
   if (p->>'driver_code')=any(crews) or (p->>'rider_code')=any(crews) or (coalesce(p->>'helper_code','')<>'' and (p->>'helper_code')=any(crews)) then raise exception 'A workforce member cannot serve two positions or vans in this plan.'; end if;
   crews:=array_append(crews,p->>'driver_code'); crews:=array_append(crews,p->>'rider_code'); if helper is not null then crews:=array_append(crews,p->>'helper_code'); end if;
   if exists(select 1 from jsonb_array_elements(ctx->'busy') b where b->>'vehicle_code'=p->>'vehicle_code' or p->>'driver_code' in (b->>'driver_code',b->>'rider_code',b->>'helper_code') or p->>'rider_code' in (b->>'driver_code',b->>'rider_code',b->>'helper_code') or (helper is not null and p->>'helper_code' in (b->>'driver_code',b->>'rider_code',b->>'helper_code'))) then raise exception 'A selected vehicle or crew member already has an active Wayplan. Refresh availability.'; end if;
   for parcel_id in select jsonb_array_elements_text(p->'delivery_way_ids') loop if parcel_id=any(ids) then raise exception 'A parcel cannot belong to two vans.'; end if; ids:=array_append(ids,parcel_id); end loop;
   select coalesce(sum(weight_kg),0) into weight from public.be_data_entry_parcel_details where delivery_way_id in (select jsonb_array_elements_text(p->'delivery_way_ids'));
   if coalesce((v->>'capacity_kg')::numeric,0)>0 and weight>(v->>'capacity_kg')::numeric then raise exception 'Selected parcel weight exceeds vehicle capacity.'; end if;
   route:=coalesce(p->'route','{}'::jsonb); route_source:=upper(coalesce(route->>'source','GEOGRAPHIC_FALLBACK')); route_mode:=coalesce(route->>'route_mode','GEOGRAPHIC_NEAREST_NEIGHBOUR_EMERGENCY');
   if route_source not in ('GOOGLE_ROUTES','MAPBOX_FALLBACK','GEOGRAPHIC_FALLBACK') then raise exception 'Invalid route source.'; end if;
 end loop;
 if short_count>1 then raise exception 'Only one delivery van may be below 50 parcels.'; end if;
 if short_count=1 and (coalesce((p_payload->>'approve_below_minimum')::boolean,false) is not true or length(reason)<5) then raise exception 'Operator approval and a reason are required for the van below 50 parcels.'; end if;
 perform 1 from public.be_data_entry_parcel_details where delivery_way_id=any(ids) order by delivery_way_id for update;

 for p in select value from jsonb_array_elements(plans) loop
   idx:=idx+1; plan_id:='WP-'||to_char(now(),'YYYYMMDD')||'-'||request_id||'-'||idx;
   select x into v from jsonb_array_elements(ctx->'vehicles') x where x->>'id'=p->>'vehicle_code';
   select x into driver from jsonb_array_elements(ctx->'drivers') x where x->>'id'=p->>'driver_code';
   select x into rider from jsonb_array_elements(ctx->'riders') x where x->>'id'=p->>'rider_code';
   select x into helper from jsonb_array_elements(ctx->'helpers') x where x->>'id'=p->>'helper_code';
   result:=public.be_generate_wayplan(p||jsonb_build_object('wayplan_id',plan_id,'region_code',region,'vehicle_name',v->>'name','driver_name',driver->>'name','rider_code',rider->>'id','rider_name',rider->>'name','helper_name',coalesce(helper->>'name',''),'actor',actor));
   if not coalesce((result->>'ok')::boolean,false) then raise exception '%',coalesce(result->>'error','Wayplan creation failed.'); end if;
   update public.be_wayplan_dispatches set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('multi_van_request',request_id,'operator_id',auth.uid(),'below_minimum',jsonb_array_length(p->'delivery_way_ids')<50,'below_minimum_reason',reason) where wayplan_id=plan_id;
   update public.be_wayplan_dispatch_stops set stop_sequence=stop_sequence+100000 where wayplan_id=plan_id;
   update public.be_wayplan_dispatch_stops s set stop_sequence=x.ord::int,optimized_sequence=x.ord::int,route_code=plan_id||'-RV001',metadata=coalesce(s.metadata,'{}'::jsonb)||jsonb_build_object('generated_route_version',1,'active_route_version',1,'active_route_sequence',x.ord::int)
   from jsonb_array_elements_text(p->'delivery_way_ids') with ordinality x(id,ord) where s.wayplan_id=plan_id and s.delivery_way_id=x.id;

   route:=coalesce(p->'route','{}'::jsonb); route_source:=upper(coalesce(route->>'source','GEOGRAPHIC_FALLBACK')); route_mode:=coalesce(route->>'route_mode','GEOGRAPHIC_NEAREST_NEIGHBOUR_EMERGENCY');
   select coalesce(jsonb_agg(jsonb_build_object('delivery_way_id',s.delivery_way_id,'sequence',s.stop_sequence,'waybill_no',s.waybill_no,'recipient_name',s.recipient_name,'recipient_phone',s.recipient_phone,'address',s.address,'township',s.township) order by s.stop_sequence),'[]'::jsonb) into delivery_json from public.be_wayplan_dispatch_stops s where s.wayplan_id=plan_id;
   select coalesce(jsonb_agg(x.value order by x.ord desc),'[]'::jsonb) into load_json from jsonb_array_elements(delivery_json) with ordinality x(value,ord);
   insert into public.be_wayplan_route_versions_v1(wayplan_id,route_version,route_scope,route_source,route_mode,ordered_stops,distance_m,duration_s,request_count,generated_by,metadata)
   values(plan_id,1,'GENERATED',route_source,route_mode,delivery_json,greatest(coalesce(nullif(route->>'distance_m','')::bigint,0),0),greatest(coalesce(nullif(route->>'duration_s','')::bigint,0),0),greatest(coalesce(nullif(route->>'request_count','')::integer,0),0),actor,jsonb_build_object('fallback',coalesce((route->>'fallback')::boolean,false),'warning',route->>'warning','optimized_at',route->>'optimized_at'));
   insert into public.be_wayplan_warehouse_load_snapshot_v1(wayplan_id,generated_route_version,delivery_order,load_order,created_by,metadata)
   values(plan_id,1,delivery_json,load_json,actor,jsonb_build_object('load_strategy','LIFO','immutable_pre_dispatch_route',true));
   update public.be_wayplan_dispatches set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('generated_route_version',1,'active_route_version',1,'warehouse_generated_route_version',1,'active_route_source',route_source,'active_route_mode',route_mode) where wayplan_id=plan_id;
   results:=results||jsonb_build_array(result||jsonb_build_object('generated_route_version',1,'route_source',route_source));
   if jsonb_array_length(p->'delivery_way_ids')<50 then insert into public.be_audit_events(actor_id,actor_email,actor_role,action,resource_type,resource_id,details) values(auth.uid(),actor,public.be_current_user_role(),'MULTI_VAN_BELOW_MINIMUM_APPROVED','WAYPLAN',plan_id,jsonb_build_object('vehicle',v,'parcel_count',jsonb_array_length(p->'delivery_way_ids'),'reason',reason,'request_id',request_id)); end if;
 end loop;
 result:=jsonb_build_object('ok',true,'wayplans',results,'parcel_count',total_count);
 insert into public.be_audit_events(actor_id,actor_email,actor_role,action,resource_type,resource_id,details) values(auth.uid(),actor,public.be_current_user_role(),'MULTI_VAN_CREATED','WAYPLAN_BATCH',request_id,jsonb_build_object('request',p_payload,'result',result,'actor_id',auth.uid()));
 return result;
end $$;
revoke all on function public.be_generate_multi_van(jsonb) from public,anon;
grant execute on function public.be_generate_multi_van(jsonb) to authenticated;

comment on table public.be_wayplan_route_versions_v1 is 'Append-only Wayplan route history. Generated and Rider reroute versions are never overwritten.';
comment on table public.be_wayplan_warehouse_load_snapshot_v1 is 'Immutable warehouse LIFO snapshot tied only to the generated pre-dispatch route.';
